/*
 * Categoria.java
 *
 * Created on 14 de Agosto de 2007, 08:29
 */

package arrancada.Formularios;

import arrancada.Relatorios.GeraRelatorio;
import arrancada.Util.TeclaPress;
import arrancada.Util.ManipularJTable;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author  monitor
 */
public class Categoria extends javax.swing.JDialog {
    
    /** Creates new form Categoria */
    public Categoria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centralizar();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelPesquisa = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jLabelBusca = new javax.swing.JLabel();
        jScrollPanePiloto = new javax.swing.JScrollPane();
        jTableCategoria = new javax.swing.JTable();
        jMenuBarCategoria = new javax.swing.JMenuBar();
        jMenuInclusao = new javax.swing.JMenu();
        jMenuAlteracao = new javax.swing.JMenu();
        jMenuExclucao = new javax.swing.JMenu();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuFechar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Categoria");
        setFocusable(false);
        setModal(true);
        setName("Categoria"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("[F2] Código  [F3] Nome");
        jLabel1.setToolTipText("\"Tecle [F2] para pesquisar por CÓDIGO,[F3] para pesquisar por NOME\"");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPesquisa.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelPesquisa.setText("Pesquisando por Código");

        jTextFieldPesquisa.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPesquisa.setToolTipText("\"Campo em branco lista todos\"");
        jTextFieldPesquisa.setName("jLabelPesquisa"); // NOI18N
        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
        });

        jLabelBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/search_f2.png"))); // NOI18N
        jLabelBusca.setName("jLabelImagem"); // NOI18N
        jLabelBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBuscaMouseClicked(evt);
            }
        });

        jScrollPanePiloto.setFocusable(false);

        jTableCategoria.setAutoCreateRowSorter(true);
        jTableCategoria.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ));
        jTableCategoria.setFocusable(false);
        jTableCategoria.getTableHeader().setReorderingAllowed(false);
        jTableCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableCategoriaKeyPressed(evt);
            }
        });
        jScrollPanePiloto.setViewportView(jTableCategoria);

        jMenuInclusao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuInclusao.setMnemonic(KeyEvent.VK_I);
        jMenuInclusao.setText("INCLUSÃO");
        jMenuInclusao.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuInclusao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuInclusaoMouseClicked(evt);
            }
        });
        jMenuBarCategoria.add(jMenuInclusao);

        jMenuAlteracao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuAlteracao.setMnemonic(KeyEvent.VK_A);
        jMenuAlteracao.setText("ALTERAÇÃO");
        jMenuAlteracao.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuAlteracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAlteracaoMouseClicked(evt);
            }
        });
        jMenuBarCategoria.add(jMenuAlteracao);

        jMenuExclucao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuExclucao.setMnemonic(KeyEvent.VK_E);
        jMenuExclucao.setText("EXCLUSÃO");
        jMenuExclucao.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuExclucao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuExclucaoMouseClicked(evt);
            }
        });
        jMenuBarCategoria.add(jMenuExclucao);

        jMenuRelatorios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuRelatorios.setMnemonic(KeyEvent.VK_R);
        jMenuRelatorios.setText("RELATÓRIO");
        jMenuRelatorios.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuRelatoriosMouseClicked(evt);
            }
        });
        jMenuBarCategoria.add(jMenuRelatorios);

        jMenuFechar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuFechar.setMnemonic(KeyEvent.VK_F);
        jMenuFechar.setText("FECHAR");
        jMenuFechar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuFecharMouseClicked(evt);
            }
        });
        jMenuBarCategoria.add(jMenuFechar);

        setJMenuBar(jMenuBarCategoria);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabelPesquisa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jTextFieldPesquisa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 34, Short.MAX_VALUE)
                        .add(jLabelBusca)))
                .addContainerGap())
            .add(jScrollPanePiloto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPanePiloto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 184, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(4, 4, 4)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelBusca)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jTextFieldPesquisa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabelPesquisa)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    jTextFieldPesquisa.requestFocus();
}//GEN-LAST:event_formWindowActivated



private void jLabelBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscaMouseClicked
    // TODO add your handling code here:
    if(jTextFieldPesquisa.getText().trim().isEmpty())
    {
        manipularJtable.categoria(jTableCategoria, "", "0");
    }
    else if(jLabelPesquisa.getText().equals("Pesquisando por Código"))
    {
        manipularJtable.categoria(jTableCategoria, jTextFieldPesquisa.getText(), "1");
    }
    else if(jLabelPesquisa.getText().equals("Pesquisando por Nome"))
    {
        manipularJtable.categoria(jTableCategoria, jTextFieldPesquisa.getText(), "2");
    }
    jTableCategoria.requestFocus();
    jTableCategoria.setRowSelectionInterval(0, 0);
}//GEN-LAST:event_jLabelBuscaMouseClicked

private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed
    // TODO add your handling code here:
    jLabelPesquisa.setText(teclaPress.KeyCategoriaPiloto(evt));
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {        
        //manipularJtable.selecionarValor(jTableCategoria, jTextFieldPesquisa.getText(), 0);
        if(jTextFieldPesquisa.getText().trim().isEmpty())
        {
            manipularJtable.categoria(jTableCategoria, "", "0");
        }
        else if(jLabelPesquisa.getText().equals("Pesquisando por Código"))
        {
            manipularJtable.categoria(jTableCategoria, jTextFieldPesquisa.getText(), "1");
        }
        else if(jLabelPesquisa.getText().equals("Pesquisando por Nome"))
        {
            manipularJtable.categoria(jTableCategoria, jTextFieldPesquisa.getText(), "2");
        }
        if(jTableCategoria.getRowCount() > 0)
        {
            jTableCategoria.requestFocus();
            jTableCategoria.setRowSelectionInterval(0, 0);
        }
    }
}//GEN-LAST:event_jTextFieldPesquisaKeyPressed

private void jMenuFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuFecharMouseClicked
    dispose();
}//GEN-LAST:event_jMenuFecharMouseClicked

    private void jMenuInclusaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuInclusaoMouseClicked
        gerenciacategoria.setTitle("Inclusão de Categoria");
        gerenciacategoria.clikmenu = "0";
        gerenciacategoria.setVisible(true);        
}//GEN-LAST:event_jMenuInclusaoMouseClicked

    private void jMenuAlteracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAlteracaoMouseClicked
        // Se a linha for == -1 siginifica que não tem linha selecionada
        if(jTableCategoria.getSelectedRow() != -1)
        {
            //Altera o Título da janela
            gerenciacategoria.setTitle("Alteração de Categoria");
            gerenciacategoria.clikmenu = "1";
            gerenciacategoria.codigo = String.valueOf(jTableCategoria.getValueAt(jTableCategoria.getSelectedRow() ,0));
            gerenciacategoria.setVisible(true);
        }
        else
        {
            //Exibe Mensagem caso nenhuma linha esteja selecionada
            JOptionPane.showMessageDialog(this, "Selecione uma Categoria na tabela.");
        }   
}//GEN-LAST:event_jMenuAlteracaoMouseClicked

    private void jMenuExclucaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExclucaoMouseClicked
        // Se a linha for == -1 siginifica que não tem linha selecionada
        if(jTableCategoria.getSelectedRow() != -1)
        {
            gerenciacategoria.setTitle("Exclusão de Categoria");
            gerenciacategoria.clikmenu = "2";
            gerenciacategoria.codigo = String.valueOf(jTableCategoria.getValueAt(jTableCategoria.getSelectedRow() ,0));
            gerenciacategoria.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Selecione uma Categoria na tabela.");
        }       
}//GEN-LAST:event_jMenuExclucaoMouseClicked
 
        
        private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            //Se não tiver nada no banco o método fica dando loop na mensagem de erro        
             
        }//GEN-LAST:event_formWindowOpened

        private void jMenuRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuRelatoriosMouseClicked
//               try {
//
//             new GeraRelatorio().montaRelatorio(4,"Categoria");
//              
//             } catch (JRException ex)
//             {
//             JOptionPane.showMessageDialog(null,ex.getMessage());              
//              }

		new ConfiguraRelatorioCategoria(null,true).setVisible(true);
        }//GEN-LAST:event_jMenuRelatoriosMouseClicked

        private void jTableCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableCategoriaKeyPressed
    if((evt.getKeyCode() == KeyEvent.VK_F2) ||(evt.getKeyCode() == KeyEvent.VK_F3))
        {
            jLabelPesquisa.setText(teclaPress.KeyCategoriaPiloto(evt));
            jTextFieldPesquisa.requestFocus();
        }           
}//GEN-LAST:event_jTableCategoriaKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Categoria dialog = new Categoria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void centralizar(){  
      /* Função para centralizar janela na tela */  
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();  
       Dimension frameSize = getSize();  
       setLocation(new Point((screenSize.width - frameSize.width) / 2,  
                             (screenSize.height - frameSize.width) / 2));  
    }  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBusca;
    private javax.swing.JLabel jLabelPesquisa;
    private javax.swing.JMenu jMenuAlteracao;
    private javax.swing.JMenuBar jMenuBarCategoria;
    private javax.swing.JMenu jMenuExclucao;
    private javax.swing.JMenu jMenuFechar;
    private javax.swing.JMenu jMenuInclusao;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JScrollPane jScrollPanePiloto;
    private javax.swing.JTable jTableCategoria;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
    
    GerenciaCategoria gerenciacategoria = new  GerenciaCategoria(null,true);
    TeclaPress teclaPress = new TeclaPress();
    ManipularJTable manipularJtable = new ManipularJTable();
    int cont = 0;
}
