/*
 * Competidor.java
 *
 * Created on 14 de Agosto de 2007, 08:42
 */

package arrancada.Formularios;

import arrancada.Relatorios.GeraRelatorio;
import arrancada.Util.TeclaPress;
import arrancada.Util.ManipularJTable;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author  monitor
 */
public class Competidor extends javax.swing.JDialog {
    
    /** Creates new form Competidor */
    public Competidor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centralizar();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneCompetidor = new javax.swing.JScrollPane();
        jTableCompetidor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabelPesquisa = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jLabelBusca = new javax.swing.JLabel();
        jMenuBarCompetidor = new javax.swing.JMenuBar();
        jMenuInclusao = new javax.swing.JMenu();
        jMenuAlteracao = new javax.swing.JMenu();
        jMenuExclucao = new javax.swing.JMenu();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuFechar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Competidor");
        setModal(true);
        setName("Competidor"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jScrollPaneCompetidor.setFocusable(false);

        jTableCompetidor.setAutoCreateRowSorter(true);
        jTableCompetidor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableCompetidor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº Veículo", "Competição", "Categoria", "Piloto", "Veículo", "Placa"
            }
        ));
        jTableCompetidor.setEditingColumn(0);
        jTableCompetidor.getTableHeader().setReorderingAllowed(false);
        jTableCompetidor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableCompetidorKeyPressed(evt);
            }
        });
        jScrollPaneCompetidor.setViewportView(jTableCompetidor);

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("[F2] Código    [F3] Competição    [F4] Categoria    [F5] Piloto     [F6] Veiculo");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPesquisa.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelPesquisa.setText("Pesquisando Por:");

        jTextFieldPesquisa.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
        });

        jLabelBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/search_f2.png"))); // NOI18N
        jLabelBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBuscaMouseClicked(evt);
            }
        });

        jMenuBarCompetidor.setFocusable(false);

        jMenuInclusao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuInclusao.setMnemonic(KeyEvent.VK_I);
        jMenuInclusao.setText("INCLUSÃO");
        jMenuInclusao.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuInclusao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuInclusaoMouseClicked(evt);
            }
        });
        jMenuBarCompetidor.add(jMenuInclusao);

        jMenuAlteracao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuAlteracao.setMnemonic(KeyEvent.VK_A);
        jMenuAlteracao.setText("ALTERAÇÃO");
        jMenuAlteracao.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuAlteracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAlteracaoMouseClicked(evt);
            }
        });
        jMenuBarCompetidor.add(jMenuAlteracao);

        jMenuExclucao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuExclucao.setMnemonic(KeyEvent.VK_E);
        jMenuExclucao.setText("EXCLUSÃO");
        jMenuExclucao.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuExclucao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuExclucaoMouseClicked(evt);
            }
        });
        jMenuBarCompetidor.add(jMenuExclucao);

        jMenuRelatorios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuRelatorios.setMnemonic(KeyEvent.VK_R);
        jMenuRelatorios.setText("RELATÓRIO");
        jMenuRelatorios.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuRelatoriosMouseClicked(evt);
            }
        });
        jMenuBarCompetidor.add(jMenuRelatorios);

        jMenuFechar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuFechar.setMnemonic(KeyEvent.VK_F);
        jMenuFechar.setText("FECHAR");
        jMenuFechar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuFecharMouseClicked(evt);
            }
        });
        jMenuBarCompetidor.add(jMenuFechar);

        setJMenuBar(jMenuBarCompetidor);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabelPesquisa, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextFieldPesquisa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 330, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelBusca)
                        .add(30, 30, 30)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPaneCompetidor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jScrollPaneCompetidor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabelPesquisa)
                        .add(jTextFieldPesquisa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabelBusca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jLabelBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscaMouseClicked
    // TODO add your handling code here:
    if(jTextFieldPesquisa.getText().trim().isEmpty())
    {
        manipularJTable.competidor(jTableCompetidor, "", "0");
    }
    else if(jLabelPesquisa.getText().equals("Pesquisando por Código"))
    {
        manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "1");
    }
    else if(jLabelPesquisa.getText().equals("Pesquisando por Competição"))
    {
        manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "2");
    }
    else if(jLabelPesquisa.getText().equals("Pesquisando por Categoria"))
    {
        manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "3");
    }
    else if(jLabelPesquisa.getText().equals("Pesquisando por Piloto"))
    {
        manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "4");
    }
    else if(jLabelPesquisa.getText().equals("Pesquisando por Veículo"))
    {
        manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "5");
    }
    jTableCompetidor.requestFocus();
    jTableCompetidor.setRowSelectionInterval(0, 0);
}//GEN-LAST:event_jLabelBuscaMouseClicked

private void jTableCompetidorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableCompetidorKeyPressed
    // TODO add your handling code here:
    if( (evt.getKeyCode() == KeyEvent.VK_F2) ||(evt.getKeyCode() == KeyEvent.VK_F3) ||
        (evt.getKeyCode() == KeyEvent.VK_F4) ||(evt.getKeyCode() == KeyEvent.VK_F5) ||
        (evt.getKeyCode() == KeyEvent.VK_F4) )
    {
        jLabelPesquisa.setText(teclaPress.KeyCategoriaPiloto(evt));
        jTextFieldPesquisa.requestFocus();
    }
}//GEN-LAST:event_jTableCompetidorKeyPressed

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    // TODO add your handling code here:
    jTextFieldPesquisa.requestFocus();
}//GEN-LAST:event_formWindowActivated

private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed
    // TODO add your handling code here:
    jLabelPesquisa.setText(teclaPress.KeyCompetidor(evt));        
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {        
        if(jTextFieldPesquisa.getText().trim().isEmpty())
        {
            manipularJTable.competidor(jTableCompetidor, "", "0");
        }
        else if(jLabelPesquisa.getText().equals("Pesquisando por Código"))
        {
            manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "1");
        }
        else if(jLabelPesquisa.getText().equals("Pesquisando por Competição"))
        {
            manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "2");
        }
        else if(jLabelPesquisa.getText().equals("Pesquisando por Categoria"))
        {
            manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "3");
        }
        else if(jLabelPesquisa.getText().equals("Pesquisando por Piloto"))
        {
            manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "4");
        }
        else if(jLabelPesquisa.getText().equals("Pesquisando por Veículo"))
        {
            manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "5");
        }
        
        if(jTableCompetidor.getRowCount() > 0)
        {
            jTableCompetidor.requestFocus();
            jTableCompetidor.setRowSelectionInterval(0, 0);
        }
    }
}//GEN-LAST:event_jTextFieldPesquisaKeyPressed

private void jMenuFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuFecharMouseClicked
    // TODO add your handling code here:
    cont = 0;
    dispose();
}//GEN-LAST:event_jMenuFecharMouseClicked

    private void jMenuInclusaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuInclusaoMouseClicked
        // TODO add your handling code here:
        gerenciacompetidor.setTitle("Inclusão de Competidor");
        gerenciacompetidor.clikmenu = "0";
        gerenciacompetidor.setVisible(true);
}//GEN-LAST:event_jMenuInclusaoMouseClicked

    private void jMenuAlteracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAlteracaoMouseClicked
        // Se a linha for == -1 siginifica que não tem linha selecionada
        if(jTableCompetidor.getSelectedRow() != -1)
        {
            gerenciacompetidor.setTitle("Alteração de Competidor");
            gerenciacompetidor.clikmenu = "1";           
            gerenciacompetidor.codigo = String.valueOf(jTableCompetidor.getValueAt(jTableCompetidor.getSelectedRow() ,0));
            gerenciacompetidor.competicao = String.valueOf(jTableCompetidor.getValueAt(jTableCompetidor.getSelectedRow() ,1));
            gerenciacompetidor.categoria = String.valueOf(jTableCompetidor.getValueAt(jTableCompetidor.getSelectedRow() ,2));
            gerenciacompetidor.setVisible(true);
        }
        else
        {
            //Exibe Mensagem caso nenhuma linha esteja selecionada
            JOptionPane.showMessageDialog(null, "Selecione um Competidor na tabela.");
        }  
}//GEN-LAST:event_jMenuAlteracaoMouseClicked

    private void jMenuExclucaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExclucaoMouseClicked
       // Se a linha for == -1 siginifica que não tem linha selecionada
        if(jTableCompetidor.getSelectedRow() != -1)
        {
            gerenciacompetidor.setTitle("Exclusão de Competidor");
            gerenciacompetidor.clikmenu = "2";
            gerenciacompetidor.codigo = String.valueOf(jTableCompetidor.getValueAt(jTableCompetidor.getSelectedRow() ,0));
            gerenciacompetidor.competicao = String.valueOf(jTableCompetidor.getValueAt(jTableCompetidor.getSelectedRow() ,1));
            gerenciacompetidor.categoria = String.valueOf(jTableCompetidor.getValueAt(jTableCompetidor.getSelectedRow() ,2));
            gerenciacompetidor.setVisible(true);
        }
        else
        {
            //Exibe Mensagem caso nenhuma linha esteja selecionada
            JOptionPane.showMessageDialog(null, "Selecione um Competidor na tabela.");
        }
}//GEN-LAST:event_jMenuExclucaoMouseClicked

    private void jMenuRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuRelatoriosMouseClicked

        
        new ConfiguraRelatorioCompetidor(null,true).setVisible(true);
        
    }//GEN-LAST:event_jMenuRelatoriosMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Competidor dialog = new Competidor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
   private void centralizar(){  
      /* Função para centralizar janela na tela */  
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();  
       Dimension frameSize = getSize();  
       setLocation(new Point((screenSize.width - frameSize.width) / 2,  
                             (screenSize.height - frameSize.width) / 2));  
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBusca;
    private javax.swing.JLabel jLabelPesquisa;
    private javax.swing.JMenu jMenuAlteracao;
    private javax.swing.JMenuBar jMenuBarCompetidor;
    private javax.swing.JMenu jMenuExclucao;
    private javax.swing.JMenu jMenuFechar;
    private javax.swing.JMenu jMenuInclusao;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JScrollPane jScrollPaneCompetidor;
    private javax.swing.JTable jTableCompetidor;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
    
    
    GerenciaCompetidor gerenciacompetidor = new GerenciaCompetidor(null,true);
    ManipularJTable manipularJTable = new ManipularJTable();
    TeclaPress teclaPress = new TeclaPress();
    int cont = 0;
}
