/*
 * ConfiguraRelatorioVeiculo.java
 *
 * Created on 3 de Fevereiro de 2008, 20:34
 */

package arrancada.Formularios;

import arrancada.Relatorios.GeraRelatorioVeiculo;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author  Bessa
 */
public class ConfiguraRelatorioVeiculo extends javax.swing.JDialog {
    
    /** Creates new form ConfiguraRelatorioVeiculo */
    public ConfiguraRelatorioVeiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVizualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIni = new javax.swing.JTextField();
        jTextFieldFim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTipo1 = new javax.swing.JTextField();
        jTextFieldTipo2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxOpcoes = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Veículo");

        jButtonVizualizar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButtonVizualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/kghostview.png"))); // NOI18N
        jButtonVizualizar.setText("Vizualizar");
        jButtonVizualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVizualizarMouseClicked(evt);
            }
        });
        jButtonVizualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVizualizarActionPerformed(evt);
            }
        });
        jButtonVizualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonVizualizarKeyPressed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Código :");

        jTextFieldIni.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldIni.setText("0");
        jTextFieldIni.setEnabled(false);

        jTextFieldFim.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldFim.setText("9999");
        jTextFieldFim.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Inicial");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Final");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("Tipo:");

        jTextFieldTipo1.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldTipo1.setText("0");
        jTextFieldTipo1.setEnabled(false);

        jTextFieldTipo2.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldTipo2.setText("99");
        jTextFieldTipo2.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIni, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldFim, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Opções :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Seleções :");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxOpcoes.setFont(new java.awt.Font("Tahoma", 1, 11));
        jComboBoxOpcoes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Geral", "Específico", "Tipo", "Código" }));
        jComboBoxOpcoes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxOpcoesItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jComboBoxOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jComboBoxOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonVizualizar)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonVizualizar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVizualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVizualizarMouseClicked
        try {
            if(estado==1) {
                new GeraRelatorioVeiculo().montaRelatorio(4,"Veículo",jTextFieldTipo1.getText(),jTextFieldTipo2.getText(), jTextFieldIni.getText(), jTextFieldFim.getText());
            } 
            else if(estado ==2)
            {
              new GeraRelatorioVeiculo().montaRelatorio(2,"Veículo", jTextFieldIni.getText(), jTextFieldFim.getText(),"","");   
            }
             else if(estado ==3)
            {
              new GeraRelatorioVeiculo().montaRelatorio(3,"Veículo", jTextFieldTipo1.getText(), jTextFieldTipo2.getText(),"","");   
            }
            else{
                jTextFieldIni.setEnabled(false);
                jTextFieldFim.setEnabled(false);
                new GeraRelatorioVeiculo().montaRelatorio(1,"Veículo","","","","");
            }
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_jButtonVizualizarMouseClicked

    private void jButtonVizualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVizualizarActionPerformed
        
    }//GEN-LAST:event_jButtonVizualizarActionPerformed

    private void jComboBoxOpcoesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxOpcoesItemStateChanged
        if(jComboBoxOpcoes.getSelectedItem().equals("Específico")) {
            jTextFieldIni.setEnabled(true);
            jTextFieldFim.setEnabled(true);
            jTextFieldTipo1.setEnabled(true);
            jTextFieldTipo2.setEnabled(true);
            estado =1;
        } 
        else if(jComboBoxOpcoes.getSelectedItem().equals("Código"))
        {
            jTextFieldIni.setEnabled(true);
            jTextFieldFim.setEnabled(true);
            jTextFieldTipo1.setEnabled(false);
            jTextFieldTipo2.setEnabled(false);
            jTextFieldTipo1.setText("0");
            jTextFieldTipo2.setText("99");
           estado =2 ;           
        }
        else if(jComboBoxOpcoes.getSelectedItem().equals("Tipo"))
        {
            jTextFieldIni.setEnabled(false);
            jTextFieldFim.setEnabled(false);
             jTextFieldIni.setText("0");
            jTextFieldFim.setText("9999");
            jTextFieldTipo1.setEnabled(true);
            jTextFieldTipo2.setEnabled(true);  
            estado =3 ;           
        }
        else {
            jTextFieldIni.setEnabled(false);
            jTextFieldFim.setEnabled(false);
             jTextFieldTipo1.setEnabled(false);
            jTextFieldTipo2.setEnabled(false);
            estado =0;
        }
    }//GEN-LAST:event_jComboBoxOpcoesItemStateChanged

    private void jButtonVizualizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonVizualizarKeyPressed
       
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
             try {
            if(estado==1) {
                new GeraRelatorioVeiculo().montaRelatorio(4,"Veículo",jTextFieldTipo1.getText(),jTextFieldTipo2.getText(), jTextFieldIni.getText(), jTextFieldFim.getText());
            } 
            else if(estado ==2)
            {
              new GeraRelatorioVeiculo().montaRelatorio(2,"Veículo", jTextFieldIni.getText(), jTextFieldFim.getText(),"","");   
            }
             else if(estado ==3)
            {
              new GeraRelatorioVeiculo().montaRelatorio(3,"Veículo", jTextFieldTipo1.getText(), jTextFieldTipo2.getText(),"","");   
            }
            else{
                jTextFieldIni.setEnabled(false);
                jTextFieldFim.setEnabled(false);
                new GeraRelatorioVeiculo().montaRelatorio(1,"Veículo","","","","");
            }
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        }
    }//GEN-LAST:event_jButtonVizualizarKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfiguraRelatorioVeiculo dialog = new ConfiguraRelatorioVeiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVizualizar;
    private javax.swing.JComboBox jComboBoxOpcoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldFim;
    private javax.swing.JTextField jTextFieldIni;
    private javax.swing.JTextField jTextFieldTipo1;
    private javax.swing.JTextField jTextFieldTipo2;
    // End of variables declaration//GEN-END:variables
   
    private int estado=0;
}
