/*
 * ConfiguraRelatorioPuxada.java
 *
 * Created on 4 de Fevereiro de 2008, 12:18
 */

package arrancada.Formularios;

import arrancada.Relatorios.GeraRelatorioPuxada;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author  Bessa
 */
public class ConfiguraRelatorioPuxada extends javax.swing.JDialog {
    
    /** Creates new form ConfiguraRelatorioPuxada */
    public ConfiguraRelatorioPuxada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxOpcoes = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIni = new javax.swing.JTextField();
        jTextFieldFim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCompeticao1 = new javax.swing.JTextField();
        jTextFieldCompeticao2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCategoria1 = new javax.swing.JTextField();
        jTextFieldCategoria2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        jButtonVizualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Puxada");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Opções :");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxOpcoes.setFont(new java.awt.Font("Tahoma", 1, 11));
        jComboBoxOpcoes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Selecione ---", "Geral", "Específico", "Puxada", "Competição", "Categoria", "Data" }));
        jComboBoxOpcoes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxOpcoesItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jComboBoxOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jComboBoxOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Seleções :");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Puxada :");

        jTextFieldIni.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldIni.setText("0");
        jTextFieldIni.setEnabled(false);

        jTextFieldFim.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldFim.setText("9999");
        jTextFieldFim.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Inicial");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Final");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("Competição :");

        jTextFieldCompeticao1.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldCompeticao1.setText("0");
        jTextFieldCompeticao1.setEnabled(false);

        jTextFieldCompeticao2.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldCompeticao2.setText("9999");
        jTextFieldCompeticao2.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setText("Categoria :");

        jTextFieldCategoria1.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldCategoria1.setText("0");
        jTextFieldCategoria1.setEnabled(false);

        jTextFieldCategoria2.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldCategoria2.setText("9999");
        jTextFieldCategoria2.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setText("Data  Comp:");

        dateChooserCombo1.setEnabled(false);

        dateChooserCombo2.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldIni, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextFieldCompeticao1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFim, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCompeticao2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCompeticao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCompeticao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jButtonVizualizar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButtonVizualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/kghostview.png"))); // NOI18N
        jButtonVizualizar.setText("Vizualizar");
        jButtonVizualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVizualizarMouseClicked(evt);
            }
        });
        jButtonVizualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonVizualizarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonVizualizar)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVizualizar)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxOpcoesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxOpcoesItemStateChanged
        if(jComboBoxOpcoes.getSelectedItem().equals("Específico")) {
            jTextFieldIni.setEnabled(true);
            jTextFieldFim.setEnabled(true);
            jTextFieldCompeticao1.setEnabled(true);
            jTextFieldCompeticao2.setEnabled(true);
            jTextFieldCategoria1.setEnabled(true);
            jTextFieldCategoria2.setEnabled(true);
            dateChooserCombo1.setEnabled(true);
            dateChooserCombo2.setEnabled(true);
            estado =1;
        } 
        else if(jComboBoxOpcoes.getSelectedItem().equals("Puxada")) {
          jTextFieldIni.setEnabled(true);
            jTextFieldFim.setEnabled(true);
            jTextFieldCompeticao1.setEnabled(false);
            jTextFieldCompeticao2.setEnabled(false);
            jTextFieldCategoria1.setEnabled(false);
            jTextFieldCategoria2.setEnabled(false);
            dateChooserCombo1.setEnabled(false);
            dateChooserCombo2.setEnabled(false);
            estado =-2;   
        }
        else if(jComboBoxOpcoes.getSelectedItem().equals("Competição"))  
        {
            jTextFieldIni.setEnabled(false);
            jTextFieldFim.setEnabled(false);
            jTextFieldCompeticao1.setEnabled(true);
            jTextFieldCompeticao2.setEnabled(true);
            jTextFieldCategoria1.setEnabled(false);
            jTextFieldCategoria2.setEnabled(false);
            dateChooserCombo1.setEnabled(false);
            dateChooserCombo2.setEnabled(false);   
            
            estado =2;
        }
         else if(jComboBoxOpcoes.getSelectedItem().equals("Categoria"))  
        {
            jTextFieldIni.setEnabled(false);
            jTextFieldFim.setEnabled(false);
            jTextFieldCompeticao1.setEnabled(false);
            jTextFieldCompeticao2.setEnabled(false);
            jTextFieldCategoria1.setEnabled(true);
            jTextFieldCategoria2.setEnabled(true);
            dateChooserCombo1.setEnabled(false);
            dateChooserCombo2.setEnabled(false);    
          estado =3;  
        }
          else if(jComboBoxOpcoes.getSelectedItem().equals("Data"))  
        {
            jTextFieldIni.setEnabled(false);
            jTextFieldFim.setEnabled(false);
            jTextFieldCompeticao1.setEnabled(false);
            jTextFieldCompeticao2.setEnabled(false);
            jTextFieldCategoria1.setEnabled(false);
            jTextFieldCategoria2.setEnabled(false);
            dateChooserCombo1.setEnabled(true);
            dateChooserCombo2.setEnabled(true);
            estado =4;
        }
           else if(jComboBoxOpcoes.getSelectedItem().equals("Geral"))  
        {
            jTextFieldIni.setEnabled(false);
            jTextFieldFim.setEnabled(false);
            jTextFieldCompeticao1.setEnabled(false);
            jTextFieldCompeticao2.setEnabled(false);
            jTextFieldCategoria1.setEnabled(false);
            jTextFieldCategoria2.setEnabled(false);
            dateChooserCombo1.setEnabled(false);
            dateChooserCombo2.setEnabled(false);
            estado =0;
        }
        else {
            jTextFieldIni.setEnabled(false);
            jTextFieldFim.setEnabled(false);
            jTextFieldCompeticao1.setEnabled(false);
            jTextFieldCompeticao2.setEnabled(false);
            jTextFieldCategoria1.setEnabled(false);
            jTextFieldCategoria2.setEnabled(false);
            dateChooserCombo1.setEnabled(false);
            dateChooserCombo2.setEnabled(false);
            estado =-1;
        }
    }//GEN-LAST:event_jComboBoxOpcoesItemStateChanged

    
    
    
    
    
    
    private void jButtonVizualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVizualizarMouseClicked
        try {
            if(estado==1) 
            {
                new GeraRelatorioPuxada().montaRelatorio(6,"Puxada", jTextFieldIni.getText(), jTextFieldFim.getText(),jTextFieldCompeticao1.getText(),jTextFieldCompeticao2.getText(),dateChooserCombo1.getText(),dateChooserCombo2.getText(),jTextFieldCategoria1.getText(),jTextFieldCategoria2.getText());
            } 
            else if( estado == -2)
            {
              new GeraRelatorioPuxada().montaRelatorio(2,"Puxada", jTextFieldIni.getText(), jTextFieldFim.getText(),"","","","","","");
            }
            else if( estado == 2)
            {
             new GeraRelatorioPuxada().montaRelatorio(3,"Puxada","", "",jTextFieldCompeticao1.getText(),jTextFieldCompeticao2.getText(),"","","","");   
            }
            else if( estado == 3)
            {
              new GeraRelatorioPuxada().montaRelatorio(5,"Puxada","", "","","","","",jTextFieldCategoria1.getText(),jTextFieldCategoria2.getText());      
            }
            else if( estado ==4)
            {
             new GeraRelatorioPuxada().montaRelatorio(4,"Puxada", "", "","","",dateChooserCombo1.getText(),dateChooserCombo2.getText(),"","");    
            }
            else
            {
                if(estado ==0)
                {
                  new GeraRelatorioPuxada().montaRelatorio(1,"Puxada","", "","","","","","","");     
                }
            }
            
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_jButtonVizualizarMouseClicked

    
    
    private void jButtonVizualizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonVizualizarKeyPressed
       
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
             try {
            if(estado==1) 
            {
                new GeraRelatorioPuxada().montaRelatorio(6,"Puxada", jTextFieldIni.getText(), jTextFieldFim.getText(),jTextFieldCompeticao1.getText(),jTextFieldCompeticao2.getText(),dateChooserCombo1.getText(),dateChooserCombo2.getText(),jTextFieldCategoria1.getText(),jTextFieldCategoria2.getText());
            } 
            else if( estado == -2)
            {
              new GeraRelatorioPuxada().montaRelatorio(2,"Puxada", jTextFieldIni.getText(), jTextFieldFim.getText(),"","","","","","");
            }
            else if( estado == 2)
            {
             new GeraRelatorioPuxada().montaRelatorio(3,"Puxada","", "",jTextFieldCompeticao1.getText(),jTextFieldCompeticao2.getText(),"","","","");   
            }
            else if( estado == 3)
            {
              new GeraRelatorioPuxada().montaRelatorio(5,"Puxada","", "","","","","",jTextFieldCategoria1.getText(),jTextFieldCategoria2.getText());      
            }
            else if( estado ==4)
            {
             new GeraRelatorioPuxada().montaRelatorio(4,"Puxada", "", "","","",dateChooserCombo1.getText(),dateChooserCombo2.getText(),"","");    
            }
            else
            {
                if(estado ==0)
                {
                  new GeraRelatorioPuxada().montaRelatorio(1,"Puxada","", "","","","","","","");     
                }
            }
            
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        }
        
    }//GEN-LAST:event_jButtonVizualizarKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfiguraRelatorioPuxada dialog = new ConfiguraRelatorioPuxada(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private javax.swing.JButton jButtonVizualizar;
    private javax.swing.JComboBox jComboBoxOpcoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldCategoria1;
    private javax.swing.JTextField jTextFieldCategoria2;
    private javax.swing.JTextField jTextFieldCompeticao1;
    private javax.swing.JTextField jTextFieldCompeticao2;
    private javax.swing.JTextField jTextFieldFim;
    private javax.swing.JTextField jTextFieldIni;
    // End of variables declaration//GEN-END:variables
  
    private int estado =0;

}
