/*
 * ConsultaPiloto.java
 *
 * Created on 28 de Outubro de 2007, 12:45
 */

package arrancada.Formularios;

import arrancada.Util.TeclaPress;
import arrancada.Util.ManipularJTable;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author  xp
 */
public class ConsultaPiloto extends javax.swing.JDialog {
    
    /** Creates new form ConsultaPiloto */
    public ConsultaPiloto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centralizar();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelPesquisa = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jLabelBusca = new javax.swing.JLabel();
        jScrollPanePiloto = new javax.swing.JScrollPane();
        jTablePiloto = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSelecionar = new javax.swing.JMenu();
        jMenuFechar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Piloto");
        setModal(true);
        setName("ConsultaPiloto"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("[F2] Código  [F3] Nome  [F4] UF  [F5] Cidade");
        jLabel1.setToolTipText("\"Tecle [F2] para pesquisar por CÓDIGO,[F3] para pesquisar por NOME\"");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPesquisa.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelPesquisa.setText("Pesquisando por Código");

        jTextFieldPesquisa.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPesquisa.setToolTipText("\"Campo em branco lista todos\"");
        jTextFieldPesquisa.setName("jLabelPesquisa"); // NOI18N
        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
        });

        jLabelBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/search_f2.png"))); // NOI18N
        jLabelBusca.setName("jLabelImagem"); // NOI18N
        jLabelBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBuscaMouseClicked(evt);
            }
        });

        jScrollPanePiloto.setFocusable(false);

        jTablePiloto.setAutoCreateRowSorter(true);
        jTablePiloto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTablePiloto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "UF", "Cidade"
            }
        ));
        jTablePiloto.getTableHeader().setReorderingAllowed(false);
        jTablePiloto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablePilotoKeyPressed(evt);
            }
        });
        jScrollPanePiloto.setViewportView(jTablePiloto);

        jMenuSelecionar.setMnemonic(KeyEvent.VK_S);
        jMenuSelecionar.setText("Selecionar");
        jMenuSelecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSelecionarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSelecionar);

        jMenuFechar.setMnemonic(KeyEvent.VK_F);
        jMenuFechar.setText("Fechar");
        jMenuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFecharActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuFechar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLabelBusca)))
                .addContainerGap())
            .addComponent(jScrollPanePiloto, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPanePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBusca)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPesquisa)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    
    
    
    private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed
        // TODO add your handling code here:
        jLabelPesquisa.setText(teclaPress.KeyPiloto(evt));
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) 
        {
            //manipularJtable.selecionarValor(jTableCategoria, jTextFieldPesquisa.getText(), 0);
            if(jTextFieldPesquisa.getText().trim().isEmpty()) 
            {
                manipularJtable.piloto(jTablePiloto, "", "0");
            } 
            else if(jLabelPesquisa.getText().equals("Pesquisando por Código")) 
            {
                manipularJtable.piloto(jTablePiloto, jTextFieldPesquisa.getText(), "1");
            }
            else if(jLabelPesquisa.getText().equals("Pesquisando por Nome")) 
            {
                manipularJtable.piloto(jTablePiloto, jTextFieldPesquisa.getText(), "2");
            }
            else if(jLabelPesquisa.getText().equals("Pesquisando por UF")) 
            {
                manipularJtable.piloto(jTablePiloto, jTextFieldPesquisa.getText(), "3");
            }
            else if(jLabelPesquisa.getText().equals("Pesquisando por Cidade")) 
            {
                manipularJtable.piloto(jTablePiloto, jTextFieldPesquisa.getText(), "4");
            }
            
            if(jTablePiloto.getRowCount() > 0) 
            {
                jTablePiloto.requestFocus();
                jTablePiloto.setRowSelectionInterval(0, 0);
            }
        }
    }//GEN-LAST:event_jTextFieldPesquisaKeyPressed

    private void jLabelBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscaMouseClicked
        if(jTextFieldPesquisa.getText().trim().isEmpty())
        {
            manipularJtable.piloto(jTablePiloto, "", "0");
        }
        else if(jLabelPesquisa.getText().equals("Pesquisando por Código"))
        {
            manipularJtable.piloto(jTablePiloto, jTextFieldPesquisa.getText(), "1");
        }
        else if(jLabelPesquisa.getText().equals("Pesquisando por Nome"))
        {
            manipularJtable.piloto(jTablePiloto, jTextFieldPesquisa.getText(), "2");
        }
         else if(jLabelPesquisa.getText().equals("Pesquisando por UF"))
        {
            manipularJtable.piloto(jTablePiloto, jTextFieldPesquisa.getText(), "3");
        }
         else if(jLabelPesquisa.getText().equals("Pesquisando por Cidade"))
        {
            manipularJtable.piloto(jTablePiloto, jTextFieldPesquisa.getText(), "4");
        }
            
        if(jTablePiloto.getRowCount() > 0) 
        {
            jTablePiloto.requestFocus();
            jTablePiloto.setRowSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_jLabelBuscaMouseClicked

    private void jMenuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFecharActionPerformed
        codigo = -1;
        dispose();
    }//GEN-LAST:event_jMenuFecharActionPerformed

    private void jMenuSelecionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSelecionarMouseClicked
        // Se a linha for == -1 siginifica que não tem linha selecionada
        if(jTablePiloto.getSelectedRow() != -1)
        {
            codigo = Integer.parseInt(String.valueOf(jTablePiloto.getValueAt(jTablePiloto.getSelectedRow() ,0)));
            dispose();
        }
        else
        {
            //Exibe Mensagem caso nenhuma linha esteja selecionada
            JOptionPane.showMessageDialog(null, "Selecione um Piloto na tabela.");
        }  
    }//GEN-LAST:event_jMenuSelecionarMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jTextFieldPesquisa.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void jTablePilotoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablePilotoKeyPressed
        if((evt.getKeyCode() == KeyEvent.VK_F2) ||(evt.getKeyCode() == KeyEvent.VK_F3)) 
        {
            jLabelPesquisa.setText(teclaPress.KeyCategoriaPiloto(evt));
            jTextFieldPesquisa.requestFocus();
        }
        else
        {
            if((evt.getKeyCode() == KeyEvent.VK_ENTER))
            {
               // Se a linha for == -1 siginifica que não tem linha selecionada
                if(jTablePiloto.getSelectedRow() != -1) 
                {
                    codigo = Integer.parseInt(String.valueOf(jTablePiloto.getValueAt(jTablePiloto.getSelectedRow() ,0)));
                    dispose();
                } 
                else 
                {
                    //Exibe Mensagem caso nenhuma linha esteja selecionada
                    JOptionPane.showMessageDialog(null, "Selecione um Veículo na tabela.");
                }
            }
        }
    }//GEN-LAST:event_jTablePilotoKeyPressed
    
    private void centralizar(){  
      /* Função para centralizar janela na tela */  
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();  
       Dimension frameSize = getSize(); 
       setLocation(new Point((screenSize.width - frameSize.width) / 2,  
                             (screenSize.height - frameSize.width) / 2));  
    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultaPiloto dialog = new ConsultaPiloto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBusca;
    private javax.swing.JLabel jLabelPesquisa;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFechar;
    private javax.swing.JMenu jMenuSelecionar;
    private javax.swing.JScrollPane jScrollPanePiloto;
    private javax.swing.JTable jTablePiloto;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
    
    TeclaPress teclaPress = new TeclaPress();
    ManipularJTable manipularJtable = new ManipularJTable();
    public static int codigo = -1;
}
