/*
 * ConsultaCompeticao.java
 *
 * Created on 25 de Dezembro de 2007, 03:58
 */

package arrancada.Formularios;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import arrancada.Util.TeclaPress;
import arrancada.Util.ManipularJTable;

/**
 *
 * @author  xp
 */
public class ConsultaCompetidor extends javax.swing.JDialog {
    
    /** Creates new form ConsultaCompeticao */
    public ConsultaCompetidor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centralizar();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPesquisa = new javax.swing.JLabel();
        jScrollPaneCompetidor = new javax.swing.JScrollPane();
        jTableCompetidor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jLabelBusca = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSelecionar = new javax.swing.JMenu();
        jMenuFechar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Competidor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabelPesquisa.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelPesquisa.setText("Pesquisando por Código");

        jScrollPaneCompetidor.setFocusable(false);

        jTableCompetidor.setAutoCreateRowSorter(true);
        jTableCompetidor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableCompetidor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº Veículo", "Competição", "Categoria", "Piloto", "Veículo", "Placa"
            }
        ));
        jTableCompetidor.setEditingColumn(0);
        jTableCompetidor.getTableHeader().setReorderingAllowed(false);
        jTableCompetidor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableCompetidorKeyPressed(evt);
            }
        });
        jScrollPaneCompetidor.setViewportView(jTableCompetidor);

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("[F2] Código    [F3] Competição    [F4] Categoria    [F5] Piloto     [F6] Veiculo");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldPesquisa.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
        });

        jLabelBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/search_f2.png"))); // NOI18N
        jLabelBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBuscaMouseClicked(evt);
            }
        });

        jMenuSelecionar.setMnemonic(KeyEvent.VK_S);
        jMenuSelecionar.setText("Selecionar");
        jMenuSelecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSelecionarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSelecionar);

        jMenuFechar.setMnemonic(KeyEvent.VK_F);
        jMenuFechar.setText("Fechar");
        jMenuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFecharActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuFechar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelBusca)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPaneCompetidor, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPaneCompetidor, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPesquisa)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSelecionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSelecionarMouseClicked
        // Se a linha for == -1 siginifica que não tem linha selecionada
        if(jTableCompetidor.getSelectedRow() != -1) {
            codigo = Integer.parseInt(String.valueOf(jTableCompetidor.getValueAt(jTableCompetidor.getSelectedRow() ,0)));
            nome = String.valueOf(jTableCompetidor.getValueAt(jTableCompetidor.getSelectedRow(),3));
            this.dispose();
        } else { 
            //Exibe Mensagem caso nenhuma linha esteja selecionada
            JOptionPane.showMessageDialog(null, "Selecione um Competidor na tabela.");
        }
    }//GEN-LAST:event_jMenuSelecionarMouseClicked

    private void jMenuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFecharActionPerformed
        codigo = -1;
        dispose();
    }//GEN-LAST:event_jMenuFecharActionPerformed

    private void jTableCompetidorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableCompetidorKeyPressed
        // TODO add your handling code here:
        if( (evt.getKeyCode() == KeyEvent.VK_F2) ||(evt.getKeyCode() == KeyEvent.VK_F3) ||
                (evt.getKeyCode() == KeyEvent.VK_F4) ||(evt.getKeyCode() == KeyEvent.VK_F5) ||
                (evt.getKeyCode() == KeyEvent.VK_F4) ) {
            jLabelPesquisa.setText(teclaPress.KeyCategoriaPiloto(evt));
            jTextFieldPesquisa.requestFocus();
        }
    }//GEN-LAST:event_jTableCompetidorKeyPressed

    private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed
        // TODO add your handling code here:
        jLabelPesquisa.setText(teclaPress.KeyCompetidor(evt));
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(jTextFieldPesquisa.getText().trim().isEmpty()) {
                manipularJTable.competidor(jTableCompetidor, "", "0");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Código")) {
                manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "1");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Competição")) {
                manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "2");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Categoria")) {
                manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "3");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Piloto")) {
                manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "4");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Veículo")) {
                manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "5");
            }
            
            if(jTableCompetidor.getRowCount() > 0) {
                jTableCompetidor.requestFocus();
                jTableCompetidor.setRowSelectionInterval(0, 0);
            }
        }
    }//GEN-LAST:event_jTextFieldPesquisaKeyPressed

    private void jLabelBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscaMouseClicked
        // TODO add your handling code here:
        if(jTextFieldPesquisa.getText().trim().isEmpty()) {
            manipularJTable.competidor(jTableCompetidor, "", "0");
        } else if(jLabelPesquisa.getText().equals("Pesquisando por Código")) {
            manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "1");
        } else if(jLabelPesquisa.getText().equals("Pesquisando por Competição")) {
            manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "2");
        } else if(jLabelPesquisa.getText().equals("Pesquisando por Categoria")) {
            manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "3");
        } else if(jLabelPesquisa.getText().equals("Pesquisando por Piloto")) {
            manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "4");
        } else if(jLabelPesquisa.getText().equals("Pesquisando por Veículo")) {
            manipularJTable.competidor(jTableCompetidor, jTextFieldPesquisa.getText().toUpperCase(), "5");
        }
        jTableCompetidor.requestFocus();
        jTableCompetidor.setRowSelectionInterval(0, 0);
    }//GEN-LAST:event_jLabelBuscaMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jTextFieldPesquisa.requestFocus();
    }//GEN-LAST:event_formWindowActivated
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultaCompeticao dialog = new ConsultaCompeticao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void centralizar(){  
      /* Função para centralizar janela na tela */  
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();  
       Dimension frameSize = getSize();  
       setLocation(new Point((screenSize.width - frameSize.width) / 2,  
                             (screenSize.height - frameSize.width) / 2));  
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBusca;
    private javax.swing.JLabel jLabelPesquisa;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFechar;
    private javax.swing.JMenu jMenuSelecionar;
    private javax.swing.JScrollPane jScrollPaneCompetidor;
    private javax.swing.JTable jTableCompetidor;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
 
    TeclaPress teclaPress = new TeclaPress();
    ManipularJTable manipularJTable = new ManipularJTable();
    public static int codigo = -1;
    public static String nome ="";
}
