/*
 * ConsultaPuxada.java
 *
 * Created on 24 de Janeiro de 2008, 21:34
 */

package arrancada.Formularios;

import arrancada.Util.ManipularJTable;
import arrancada.Util.TeclaPress;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *Formulario criadom para que o úsuario possa ter mais opções para gerar suas consultas
 * ùltima atualização : 26/01/2008
 * @author  Bessa
 */
public class ConsultaPuxada extends javax.swing.JDialog {
    
    /** Creates new form ConsultaPuxada */
    public ConsultaPuxada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centralizar();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePuxada = new javax.swing.JTable();
        jLabelPesquisa = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jLabelBusca = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSelecionar = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTablePuxada.setAutoCreateRowSorter(true);
        jTablePuxada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Competição", "Categoria", "Competidor", "Tempo", "Status", "Puxada"
            }
        ));
        jTablePuxada.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTablePuxada);

        jLabelPesquisa.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelPesquisa.setText("Pesquisando por Código");

        jTextFieldPesquisa.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPesquisa.setToolTipText("\"Campo em branco lista todos\"");
        jTextFieldPesquisa.setName("jLabelPesquisa"); // NOI18N
        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
        });

        jLabelBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/search_f2.png"))); // NOI18N
        jLabelBusca.setName("jLabelImagem"); // NOI18N
        jLabelBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBuscaMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("[F2] Código  [F3] Competição  [F4] Categoria  [F5] Competidor");
        jLabel1.setToolTipText("\"Tecle [F2] para pesquisar por CÓDIGO,[F3] para pesquisar por NOME\"");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenuSelecionar.setMnemonic(KeyEvent.VK_S);
        jMenuSelecionar.setText("Selecionar");
        jMenuSelecionar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuSelecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSelecionarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSelecionar);

        jMenu2.setMnemonic(KeyEvent.VK_F);
        jMenu2.setText("Fechar");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPesquisa))
                    .addComponent(jLabelBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed

         jLabelPesquisa.setText(teclaPress.KeyPuxada(evt));
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if(jTextFieldPesquisa.getText().trim().isEmpty()) {
                manipularJtable.puxada(jTablePuxada,"","1");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Código")) {
                manipularJtable.puxada(jTablePuxada,jTextFieldPesquisa.getText(),"2");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Competição")) {
                manipularJtable.puxada(jTablePuxada,jTextFieldPesquisa.getText(),"7");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Categoria")) {
                manipularJtable.puxada(jTablePuxada,jTextFieldPesquisa.getText(),"9");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Competidor")) {
                manipularJtable.puxada(jTablePuxada,jTextFieldPesquisa.getText(),"10");
            }
            
            if(jTablePuxada.getRowCount() > 0) {
                jTablePuxada.requestFocus();
                jTablePuxada.setRowSelectionInterval(0, 0);
            }
        
        }
    }//GEN-LAST:event_jTextFieldPesquisaKeyPressed

    private void jLabelBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscaMouseClicked
        // TODO add your handling code here:
       if(jTextFieldPesquisa.getText().trim().isEmpty()) {
                manipularJtable.puxada(jTablePuxada,"","1");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Código")) {
                manipularJtable.puxada(jTablePuxada,jTextFieldPesquisa.getText(),"2");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Competição")) {
                manipularJtable.puxada(jTablePuxada,jTextFieldPesquisa.getText(),"7");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Categoria")) {
                manipularJtable.puxada(jTablePuxada,jTextFieldPesquisa.getText(),"9");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Competidor")) {
                manipularJtable.puxada(jTablePuxada,jTextFieldPesquisa.getText(),"10");
            }
            
            if(jTablePuxada.getRowCount() > 0) {
                jTablePuxada.requestFocus();
                jTablePuxada.setRowSelectionInterval(0, 0);
            }
    }//GEN-LAST:event_jLabelBuscaMouseClicked

    private void jMenuSelecionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSelecionarMouseClicked
        
        if(jTablePuxada.getSelectedRow() != -1) {
            codigo = Integer.parseInt(String.valueOf(jTablePuxada.getValueAt(jTablePuxada.getSelectedRow() ,0)));
            status = String.valueOf(jTablePuxada.getValueAt(jTablePuxada.getSelectedRow(),5));
            dispose();
        } else {
            //Exibe Mensagem caso nenhuma linha esteja selecionada
            JOptionPane.showMessageDialog(null, "Selecione uma Puxada na tabela.");
        }
}//GEN-LAST:event_jMenuSelecionarMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        
        codigo = -1;
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked
    
    
   private void centralizar(){  
      /* Função para centralizar janela na tela */  
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();  
       Dimension frameSize = getSize();  
       setLocation(new Point((screenSize.width - frameSize.width) / 2,  
                             (screenSize.height - frameSize.width) / 2));  
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultaPuxada dialog = new ConsultaPuxada(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBusca;
    private javax.swing.JLabel jLabelPesquisa;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuSelecionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePuxada;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables

    TeclaPress teclaPress = new TeclaPress();
    ManipularJTable manipularJtable = new ManipularJTable();
    public static int codigo = -1;
    public static String status ="";
    
    
    
}
