/*
 * GerenciaVeiculo.java
 *
 * Created on 14 de Agosto de 2007, 10:01
 */

package arrancada.Formularios;

import arrancada.Util.ValidarCodigoCategoria;
import arrancada.Util.Limpar;
import arrancada.Dao.ServicoBDAO;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author  monitor
 */
public class GerenciaVeiculo extends javax.swing.JDialog {
    
    /** Creates new form GerenciaVeiculo */
    public GerenciaVeiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centralizar();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodigo = new javax.swing.JLabel();
        jLabel2Descricao = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jComboBoxTipoVeiculo = new javax.swing.JComboBox();
        jButtonConsultaVeiculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Veiculo");
        setModal(true);
        setName("GerenciaVeiculo"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabelCodigo.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelCodigo.setText("Código:");

        jLabel2Descricao.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2Descricao.setText("Descrição:");

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelTipo.setText("Tipo:");

        jTextFieldCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCodigoFocusLost(evt);
            }
        });

        jButtonConfirmar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButtonConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/14.png"))); // NOI18N
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/15.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonFechar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/06.png"))); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jComboBoxTipoVeiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Carro", "Moto" }));

        jButtonConsultaVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/botaoconsulta.png"))); // NOI18N
        jButtonConsultaVeiculo.setFocusable(false);
        jButtonConsultaVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaVeiculoActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(27, 27, 27)
                        .add(jLabelCodigo)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jTextFieldCodigo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonConsultaVeiculo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel2Descricao)
                            .add(jLabelTipo))
                        .add(10, 10, 10)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jComboBoxTipoVeiculo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(layout.createSequentialGroup()
                                    .add(jButtonConfirmar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jButtonCancelar)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jButtonFechar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(jTextFieldNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 339, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabelCodigo)
                        .add(jTextFieldCodigo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jButtonConsultaVeiculo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2Descricao))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBoxTipoVeiculo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelTipo))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonCancelar)
                    .add(jButtonFechar)
                    .add(jButtonConfirmar))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void retornoBotao(String menu, int botao)
{
    limpar.limpajTextField(jTextFieldNome);
    if((menu.equals("0")) && ((botao == 0) || (botao == 1) ) )
    {        
        jTextFieldNome.requestFocus();
    }
    else if ((menu.equals("1")) || (menu.equals("2") ) ) 
    {
        limpar.limpajTextField(jTextFieldCodigo);
        jTextFieldCodigo.setEnabled(true);
        jComboBoxTipoVeiculo.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldCodigo.requestFocus();
    }
}       
  
private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    if(evt.getOppositeWindow() instanceof Veiculo)
    {
        jButtonConsultaVeiculo.setVisible(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldNome.setText("");
        jComboBoxTipoVeiculo.setEnabled(true);
        if(this.getTitle().equals("Inclusão de Veículo"))
        {
            jButtonConsultaVeiculo.setVisible(false);
            String zeros = "0000"+servico.proximoCodigo("veiculo");
            jTextFieldCodigo.setText(zeros.substring(zeros.length()-4));
            jTextFieldCodigo.setEnabled(false);
        }
        else
        {
            try
            {
                ResultSet rs = servico.selectVeiculo(String.valueOf(Integer.parseInt(codigo)), "1");
                if(rs.next() != false)
                {
                    jTextFieldCodigo.setEnabled(true);
                    jTextFieldCodigo.setText(codigo);
                    jTextFieldCodigo.setEnabled(false);
                    jTextFieldNome.setText(rs.getString(2));
                    jComboBoxTipoVeiculo.setSelectedIndex(rs.getInt(3));
                    codigo = "";
                }
            }
            catch (SQLException ex) 
            {
                Logger.getLogger(GerenciaVeiculo.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(this.getTitle().equals("Alteração de Veículo"))
            {
               jTextFieldNome.setEnabled(true); 
               jTextFieldNome.requestFocus();
               jComboBoxTipoVeiculo.setEnabled(true);
            }
            else
            {
                jTextFieldNome.setEnabled(false);
                jComboBoxTipoVeiculo.setEnabled(false);
            }
            
        }
    }
}//GEN-LAST:event_formWindowActivated

private void jTextFieldCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCodigoFocusLost
    if (evt.getOppositeComponent() instanceof JButton || evt.getComponent() instanceof JOptionPane || clicouBotaoPesquisa == 1)
    {
        clicouBotaoPesquisa = 0;
        return;
    }
    else
    {
        try 
        {
            ServicoBDAO servico = new ServicoBDAO();
            String zeros = "0000" + jTextFieldCodigo.getText().trim();
            jTextFieldCodigo.setText(zeros.substring(zeros.length() - 4));
            int codformatado = Integer.parseInt(jTextFieldCodigo.getText().trim());////
            ResultSet rs = servico.selectVeiculo(Integer.toString(codformatado), "1");
            if (rs.next() == false) 
            {
                rs.close();
                limpar.limpajTextField(jTextFieldNome);
                jTextFieldCodigo.requestFocus();
                if(this.getTitle().equals("Exclusão de Veículo"))
                {
                    JOptionPane.showMessageDialog(null,"Código não Cadastrado","Atenção",JOptionPane.INFORMATION_MESSAGE);
                    jTextFieldCodigo.selectAll();
                    return;
                }
                else if(this.getTitle().equals("Alteração de Veículo"))
                {
                    JOptionPane.showMessageDialog(null,"Código não Cadastrado","Atenção",JOptionPane.INFORMATION_MESSAGE);
                    jTextFieldCodigo.selectAll();
                    return;
                }
            }
            else
            {
                jTextFieldCodigo.setEnabled(false);
                jTextFieldNome.setEnabled(true);
                jTextFieldNome.setText(rs.getString(2));
                jComboBoxTipoVeiculo.setEnabled(true);
                jComboBoxTipoVeiculo.setSelectedIndex(rs.getInt(3));
                if(this.getTitle().equals("Exclusão de Veículo"))
                {
                    jTextFieldNome.setEnabled(false);
                    jComboBoxTipoVeiculo.setEnabled(false);
                }
            }
        }
        catch (SQLException ex) 
        {
            Logger.getLogger(ValidarCodigoCategoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}//GEN-LAST:event_jTextFieldCodigoFocusLost

private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
    limpar.limpajTextField(jTextFieldNome);
    dispose();
}//GEN-LAST:event_jButtonFecharActionPerformed

private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
    retornoBotao(clikmenu, 1);
}//GEN-LAST:event_jButtonCancelarActionPerformed

private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
    if(jTextFieldCodigo.getText().equals(""))
    {
        jTextFieldCodigo.requestFocus();
        JOptionPane.showMessageDialog(this, "Compo código não pode ficar vazio", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    else
    {
        if(jTextFieldNome.getText().equals(""))
        {
            jTextFieldNome.requestFocus();
            JOptionPane.showMessageDialog(this, "Compo nome não pode ficar vazio", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        else
        {
            if(this.getTitle().equals("Inclusão de Veículo"))
            {
                int retorno = servico.insertVeiculo(jTextFieldCodigo.getText(), jTextFieldNome.getText(), Integer.toString(jComboBoxTipoVeiculo.getSelectedIndex()));
                if(retorno == 1)
                {
                    String zeros = "0000"+servico.proximoCodigo("veiculo");
                    jTextFieldCodigo.setText(zeros.substring(zeros.length()-4));
                    jTextFieldNome.setText("");
                    jTextFieldNome.requestFocus();
                    JOptionPane.showMessageDialog(this, "Veículo incluído com sucesso.");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Não foi possível incluir o Veículo, verifique os dados.");
                }
            }
            else if(this.getTitle().equals("Alteração de Veículo"))
            {
                int retorno = servico.updateVeiculo(jTextFieldCodigo.getText(), jTextFieldNome.getText(), Integer.toString(jComboBoxTipoVeiculo.getSelectedIndex()));
                if(retorno == 1)
                {
                    limpar.limpajTextField(jTextFieldNome);
                    retornoBotao(clikmenu, 1);
                    codigo = "";
                    JOptionPane.showMessageDialog(this, "Veículo Alterado com Sucesso.", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    jTextFieldCodigo.requestFocus();
                    JOptionPane.showMessageDialog(this, "Veículo não pode ser alterado.", "Mensagem", JOptionPane.ERROR_MESSAGE);
                }
            }
            else if(this.getTitle().equals("Exclusão de Veículo"))
            {
                    try 
                    {
                        ResultSet rs = servico.selectCompetidor(String.valueOf(Integer.parseInt(jTextFieldCodigo.getText())), "", "", "6");
                        if (rs.next() == false) 
                        {
                            int retorno = servico.deleteVeiculo(jTextFieldCodigo.getText());
                            if (retorno == 1) 
                            {
                                limpar.limpajTextField(jTextFieldNome);
                                retornoBotao(clikmenu, 1);
                                codigo = "";
                                JOptionPane.showMessageDialog(this, "Veículo Excluído com Sucesso", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
                            }
                            else 
                            {
                                jTextFieldCodigo.requestFocus();
                                JOptionPane.showMessageDialog(this, "Veículo não pode ser Excluído", "Mensagem", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                        else 
                        {
                            jTextFieldCodigo.requestFocus();
                            JOptionPane.showMessageDialog(this, "Veículo não pode ser Excluído porque existe um competidor utilizando o mesmo!", "Mensagem", JOptionPane.ERROR_MESSAGE);
                        }
                        
                    } 
                    catch (SQLException ex) 
                    {
                        Logger.getLogger(GerenciaVeiculo.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
        }
    }
}//GEN-LAST:event_jButtonConfirmarActionPerformed

private void jButtonConsultaVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaVeiculoActionPerformed
    //codigo = "";
    clicouBotaoPesquisa = 1;
    retornoBotao(clikmenu, 1);
    ConsultaVeiculo consultaVeiculo = new ConsultaVeiculo(null, true);
    consultaVeiculo.setVisible(true);
    if(consultaVeiculo.codigo != -1)
    {
        jTextFieldCodigo.setText(Integer.toString(consultaVeiculo.codigo));
        jTextFieldCodigo.transferFocus();
    }
}//GEN-LAST:event_jButtonConsultaVeiculoActionPerformed

private void centralizar()
{  
      /* Função para centralizar janela na tela */  
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();  
       Dimension frameSize = getSize();  
       setLocation(new Point((screenSize.width - frameSize.width) / 2,  
                             (screenSize.height - frameSize.width) / 2));  
    }  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GerenciaVeiculo dialog = new GerenciaVeiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonConsultaVeiculo;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JComboBox jComboBoxTipoVeiculo;
    private javax.swing.JLabel jLabel2Descricao;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
 
    public String clikmenu;  
    Limpar limpar = new Limpar();
    ServicoBDAO servico = new ServicoBDAO();
    public String codigo;
    private int clicouBotaoPesquisa = 0;
}
