/*
 * Piloto.java
 *
 * Created on 14 de Agosto de 2007, 08:57
 */

package arrancada.Formularios;

import arrancada.Relatorios.GeraRelatorio;
import arrancada.Util.TeclaPress;
import arrancada.Util.ManipularJTable;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author  monitor
 */
public class Piloto extends javax.swing.JDialog {
    
    /** Creates new form Piloto */
    public Piloto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centralizar();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanePiloto = new javax.swing.JScrollPane();
        jTablePiloto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabelPesquisa = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jLabelBusca = new javax.swing.JLabel();
        jMenuBarPiloto = new javax.swing.JMenuBar();
        jMenuInclusao = new javax.swing.JMenu();
        jMenuAlteracao = new javax.swing.JMenu();
        jMenuExclucao = new javax.swing.JMenu();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuFechar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Piloto");
        setModal(true);
        setName("Piloto"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jScrollPanePiloto.setFocusable(false);

        jTablePiloto.setAutoCreateRowSorter(true);
        jTablePiloto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTablePiloto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "UF", "Cidade"
            }
        ));
        jTablePiloto.setFocusable(false);
        jTablePiloto.getTableHeader().setReorderingAllowed(false);
        jTablePiloto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablePilotoKeyPressed(evt);
            }
        });
        jScrollPanePiloto.setViewportView(jTablePiloto);

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("[F2] Código    [F3] Nome    [F4] UF    [F5] Cidade");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPesquisa.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelPesquisa.setText("Pesquisando por Código");

        jTextFieldPesquisa.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
        });

        jLabelBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/search_f2.png"))); // NOI18N
        jLabelBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBuscaMouseClicked(evt);
            }
        });

        jMenuBarPiloto.setFocusable(false);

        jMenuInclusao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuInclusao.setMnemonic(KeyEvent.VK_I);
        jMenuInclusao.setText("INCLUSÃO");
        jMenuInclusao.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuInclusao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuInclusaoMouseClicked(evt);
            }
        });
        jMenuBarPiloto.add(jMenuInclusao);

        jMenuAlteracao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuAlteracao.setMnemonic(KeyEvent.VK_A);
        jMenuAlteracao.setText("ALTERAÇÃO");
        jMenuAlteracao.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuAlteracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAlteracaoMouseClicked(evt);
            }
        });
        jMenuBarPiloto.add(jMenuAlteracao);

        jMenuExclucao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuExclucao.setMnemonic(KeyEvent.VK_E);
        jMenuExclucao.setText("EXCLUSÃO");
        jMenuExclucao.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuExclucao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuExclucaoMouseClicked(evt);
            }
        });
        jMenuBarPiloto.add(jMenuExclucao);

        jMenuRelatorio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuRelatorio.setMnemonic(KeyEvent.VK_R);
        jMenuRelatorio.setText("RELATÓRIO");
        jMenuRelatorio.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuRelatorioMouseClicked(evt);
            }
        });
        jMenuBarPiloto.add(jMenuRelatorio);

        jMenuFechar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuFechar.setMnemonic(KeyEvent.VK_F);
        jMenuFechar.setText("FECHAR");
        jMenuFechar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuFecharMouseClicked(evt);
            }
        });
        jMenuBarPiloto.add(jMenuFechar);

        setJMenuBar(jMenuBarPiloto);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabelPesquisa)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 26, Short.MAX_VALUE)
                        .add(jTextFieldPesquisa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 258, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabelBusca)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPanePiloto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jScrollPanePiloto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 184, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabelPesquisa)
                        .add(jTextFieldPesquisa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabelBusca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed
    jLabelPesquisa.setText(teclaPress.KeyPiloto(evt));
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {        
        if(jTextFieldPesquisa.getText().trim().isEmpty())
        {
            manipularJtable.piloto(jTablePiloto, "", "0");
        }
        else if(jLabelPesquisa.getText().equals("Pesquisando por Código"))
        {
            manipularJtable.piloto(jTablePiloto, jTextFieldPesquisa.getText(), "1");
        }
        else if(jLabelPesquisa.getText().equals("Pesquisando por Nome"))
        {
            manipularJtable.piloto(jTablePiloto, jTextFieldPesquisa.getText(), "2");
        }
         else if(jLabelPesquisa.getText().equals("Pesquisando por UF"))
        {
            manipularJtable.piloto(jTablePiloto, jTextFieldPesquisa.getText(), "3");
        }
         else if(jLabelPesquisa.getText().equals("Pesquisando por Cidade"))
        {
            manipularJtable.piloto(jTablePiloto, jTextFieldPesquisa.getText(), "4");
        }
        if(jTablePiloto.getRowCount() > 0)
        {
            jTablePiloto.requestFocus();
            jTablePiloto.setRowSelectionInterval(0, 0);
        }
    }
}//GEN-LAST:event_jTextFieldPesquisaKeyPressed

private void jMenuFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuFecharMouseClicked
    dispose();
}//GEN-LAST:event_jMenuFecharMouseClicked

    private void jMenuInclusaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuInclusaoMouseClicked
        gerenciapiloto.setTitle("Inclusão de Piloto");
        gerenciapiloto.clikmenu = "0";
        gerenciapiloto.setVisible(true);
}//GEN-LAST:event_jMenuInclusaoMouseClicked

    private void jMenuAlteracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAlteracaoMouseClicked
        if(jTablePiloto.getSelectedRow() != -1)
        {
            gerenciapiloto.setTitle("Alteração de Piloto");
            gerenciapiloto.clikmenu = "1";
            gerenciapiloto.codigo = String.valueOf(jTablePiloto.getValueAt(jTablePiloto.getSelectedRow(),0));          
            gerenciapiloto.setVisible(true);
        }
        else
        {
            //Exibe Mensagem caso nenhuma linha esteja selecionada
            JOptionPane.showMessageDialog(this, "Selecione um Piloto na tabela.");
        }
}//GEN-LAST:event_jMenuAlteracaoMouseClicked

    private void jMenuExclucaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExclucaoMouseClicked
        if(jTablePiloto.getSelectedRow() != -1)
        {
            gerenciapiloto.setTitle("Exclusão de Piloto");
            gerenciapiloto.clikmenu = "2";
            gerenciapiloto.codigo = String.valueOf(jTablePiloto.getValueAt(jTablePiloto.getSelectedRow() ,0));
            gerenciapiloto.setVisible(true);
        }
        else
        {
            //Exibe Mensagem caso nenhuma linha esteja selecionada
            JOptionPane.showMessageDialog(this, "Selecione um Piloto na tabela.");
        }   
}//GEN-LAST:event_jMenuExclucaoMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jTextFieldPesquisa.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void jTablePilotoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablePilotoKeyPressed
        if((evt.getKeyCode() == KeyEvent.VK_F2) ||(evt.getKeyCode() == KeyEvent.VK_F3))
        {
            jLabelPesquisa.setText(teclaPress.KeyPiloto(evt));
            jTextFieldPesquisa.requestFocus();
        }
    }//GEN-LAST:event_jTablePilotoKeyPressed

    private void jLabelBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscaMouseClicked
        if(jTextFieldPesquisa.getText().trim().isEmpty())
        {
            manipularJtable.piloto(jTablePiloto, "", "0");
        }
        else if(jLabelPesquisa.getText().equals("Pesquisando por Código"))
        {
            manipularJtable.piloto(jTablePiloto, jTextFieldPesquisa.getText(), "1");
        }
        else if(jLabelPesquisa.getText().equals("Pesquisando por Nome"))
        {
            manipularJtable.piloto(jTablePiloto, jTextFieldPesquisa.getText(), "2");
        }
         else if(jLabelPesquisa.getText().equals("Pesquisando por UF"))
        {
            manipularJtable.piloto(jTablePiloto, jTextFieldPesquisa.getText(), "3");
        }
         else if(jLabelPesquisa.getText().equals("Pesquisando por Cidade"))
        {
            manipularJtable.piloto(jTablePiloto, jTextFieldPesquisa.getText(), "4");
        }
        jTablePiloto.requestFocus();
        jTablePiloto.setRowSelectionInterval(0, 0);
    }//GEN-LAST:event_jLabelBuscaMouseClicked

    private void jMenuRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuRelatorioMouseClicked
      
//        try {
//
//             new GeraRelatorio().montaRelatorio(1,"Piloto");
//              
//             } catch (JRException ex)
//             {
//             JOptionPane.showMessageDialog(null,ex.getMessage());              
//              }
        
         new ConfiguraRelatorioPiloto(null,true).setVisible(true);
    }//GEN-LAST:event_jMenuRelatorioMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Piloto dialog = new Piloto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
   private void centralizar(){  
      /* Função para centralizar janela na tela */  
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();  
       Dimension frameSize = getSize();  
       setLocation(new Point((screenSize.width - frameSize.width) / 2,  
                             (screenSize.height - frameSize.width) / 2));  
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBusca;
    private javax.swing.JLabel jLabelPesquisa;
    private javax.swing.JMenu jMenuAlteracao;
    private javax.swing.JMenuBar jMenuBarPiloto;
    private javax.swing.JMenu jMenuExclucao;
    private javax.swing.JMenu jMenuFechar;
    private javax.swing.JMenu jMenuInclusao;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JScrollPane jScrollPanePiloto;
    private javax.swing.JTable jTablePiloto;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
    
    GerenciaPiloto gerenciapiloto = new GerenciaPiloto(null,true);
    ManipularJTable manipularJtable = new ManipularJTable();
    TeclaPress teclaPress = new TeclaPress();
    int cont = 0;
}
