/*
 * Principal.java
 *
 * Created on 14 de Agosto de 2007, 08:13
 */

package arrancada.Formularios;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author  monitor
 */
public class Principal extends javax.swing.JFrame {
    
    /** Creates new form Principal */
    public Principal() {
        initComponents();
        centralizar();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuArrancada = new javax.swing.JMenuBar();
        jMenuGerenciar = new javax.swing.JMenu();
        jMenuPiloto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuVeiculo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuCompetiçao = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        jMenuCompetidor = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        jMenuCategoria = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JSeparator();
        jMenuItem2 = new javax.swing.JMenuItem();
        Arrancada = new javax.swing.JMenu();
        jMenuPuxada = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JSeparator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuFechar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KM Arrancada");
        setName("Principal"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jMenuGerenciar.setMnemonic(KeyEvent.VK_G);
        jMenuGerenciar.setText("Gerenciador");
        jMenuGerenciar.setFont(new java.awt.Font("Tahoma", 1, 12));

        jMenuPiloto.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuPiloto.setText("Piloto");
        jMenuPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPilotoActionPerformed(evt);
            }
        });
        jMenuGerenciar.add(jMenuPiloto);
        jMenuGerenciar.add(jSeparator1);

        jMenuVeiculo.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuVeiculo.setText("Veículo");
        jMenuVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVeiculoActionPerformed(evt);
            }
        });
        jMenuGerenciar.add(jMenuVeiculo);
        jMenuGerenciar.add(jSeparator2);

        jMenuCompetiçao.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuCompetiçao.setText("Competição");
        jMenuCompetiçao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCompetiçaoActionPerformed(evt);
            }
        });
        jMenuGerenciar.add(jMenuCompetiçao);
        jMenuGerenciar.add(jSeparator3);

        jMenuCompetidor.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuCompetidor.setText("Competidor");
        jMenuCompetidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCompetidorActionPerformed(evt);
            }
        });
        jMenuGerenciar.add(jMenuCompetidor);
        jMenuGerenciar.add(jSeparator4);

        jMenuCategoria.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuCategoria.setText("Categoria");
        jMenuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCategoriaActionPerformed(evt);
            }
        });
        jMenuGerenciar.add(jMenuCategoria);
        jMenuGerenciar.add(jSeparator5);

        jMenuItem2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuItem2.setText("Puxada");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuGerenciar.add(jMenuItem2);

        jMenuArrancada.add(jMenuGerenciar);

        Arrancada.setMnemonic(KeyEvent.VK_A);
        Arrancada.setText("Arrancada");
        Arrancada.setFont(new java.awt.Font("Tahoma", 1, 12));

        jMenuPuxada.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuPuxada.setText("Puxada");
        jMenuPuxada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPuxadaActionPerformed(evt);
            }
        });
        Arrancada.add(jMenuPuxada);
        Arrancada.add(jSeparator6);

        jMenuItem1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuItem1.setText("Relatórios");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Arrancada.add(jMenuItem1);

        jMenuArrancada.add(Arrancada);

        jMenuFechar.setMnemonic(KeyEvent.VK_F);
        jMenuFechar.setText("Fechar");
        jMenuFechar.setFont(new java.awt.Font("Tahoma", 1, 12));
        jMenuFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuFecharMouseClicked(evt);
            }
        });
        jMenuArrancada.add(jMenuFechar);

        setJMenuBar(jMenuArrancada);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 566, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 329, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenuFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuFecharMouseClicked
    // TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_jMenuFecharMouseClicked

    private void jMenuPuxadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPuxadaActionPerformed
        puxada.setVisible(true);
    }//GEN-LAST:event_jMenuPuxadaActionPerformed

    private void jMenuPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPilotoActionPerformed
       piloto.setVisible(true);
    }//GEN-LAST:event_jMenuPilotoActionPerformed

    private void jMenuVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVeiculoActionPerformed
        veiculo.setVisible(true);
    }//GEN-LAST:event_jMenuVeiculoActionPerformed

    private void jMenuCompetiçaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCompetiçaoActionPerformed
        competicao.setVisible(true);
    }//GEN-LAST:event_jMenuCompetiçaoActionPerformed

    private void jMenuCompetidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCompetidorActionPerformed
        competidor.setVisible(true);
    }//GEN-LAST:event_jMenuCompetidorActionPerformed

    private void jMenuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCategoriaActionPerformed
        categoria.setVisible(true);       
    }//GEN-LAST:event_jMenuCategoriaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
         ImageIcon icone = new ImageIcon(getClass().getResource("/arrancada.Imagens/version_check.png"));         
            this.setIconImage(icone.getImage());
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
      // new ConfiguraRelatorioPuxada(null,true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         new ConfiguraRelatorioPuxada(null,true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         new PuxadaG(null,true).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    private void centralizar(){  
      /* Função para centralizar janela na tela */  
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();  
       Dimension frameSize = getSize();  
       setLocation(new Point((screenSize.width - frameSize.width) / 2,  
                             (screenSize.height - frameSize.width) / 2));  
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Arrancada;
    private javax.swing.JMenuBar jMenuArrancada;
    private javax.swing.JMenuItem jMenuCategoria;
    private javax.swing.JMenuItem jMenuCompetidor;
    private javax.swing.JMenuItem jMenuCompetiçao;
    private javax.swing.JMenu jMenuFechar;
    private javax.swing.JMenu jMenuGerenciar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuPiloto;
    private javax.swing.JMenuItem jMenuPuxada;
    private javax.swing.JMenuItem jMenuVeiculo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
    
    Categoria categoria = new Categoria(null,true);
    Competidor competidor = new Competidor(null,true);
    Piloto piloto = new Piloto(null,true);
    Puxada puxada = new Puxada(null,true);
    Veiculo veiculo = new Veiculo(null,true);
    Competicao competicao = new Competicao(null, true);
}
