/*
 * PuxadaG.java
 *
 * Created on 16 de Fevereiro de 2008, 23:45
 */

package arrancada.Formularios;

import arrancada.Util.ManipularJTable;
import arrancada.Util.TeclaPress;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author  Bessa
 */
public class PuxadaG extends javax.swing.JDialog {
    
    /** Creates new form PuxadaG */
    public PuxadaG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centralizar();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuPuxada = new javax.swing.JPopupMenu();
        jMenuItemAlterar = new javax.swing.JMenuItem();
        jMenuItemExcluir = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePuxada = new javax.swing.JTable();
        jLabelPesquisa = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelBusca = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAlterar = new javax.swing.JMenu();
        jMenuExcluir = new javax.swing.JMenu();

        jMenuItemAlterar.setText("Alterar");
        jMenuItemAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemAlterarMouseClicked(evt);
            }
        });
        jPopupMenuPuxada.add(jMenuItemAlterar);

        jMenuItemExcluir.setText("Excluir");
        jMenuItemExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemExcluirMouseClicked(evt);
            }
        });
        jPopupMenuPuxada.add(jMenuItemExcluir);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Puxada");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTablePuxada.setAutoCreateRowSorter(true);
        jTablePuxada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Competição", "Categoria", "Competidor", "Tempo", "Status", "Puxada"
            }
        ));
        jTablePuxada.setInheritsPopupMenu(true);
        jTablePuxada.getTableHeader().setReorderingAllowed(false);
        jTablePuxada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePuxadaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePuxada);

        jLabelPesquisa.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelPesquisa.setText("Pesquisando por Código");

        jTextFieldPesquisa.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPesquisa.setToolTipText("\"Campo em branco lista todos\"");
        jTextFieldPesquisa.setName("jLabelPesquisa"); // NOI18N
        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("[F2] Código [F3] Competição [F4] Categoria [F5] Competidor");
        jLabel1.setToolTipText("\"Tecle [F2] para pesquisar por CÓDIGO,[F3] para pesquisar por NOME\"");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/search_f2.png"))); // NOI18N
        jLabelBusca.setName("jLabelImagem"); // NOI18N
        jLabelBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBuscaMouseClicked(evt);
            }
        });

        jMenuAlterar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuAlterar.setText("ALTERAÇÃO");
        jMenuAlterar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAlterarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuAlterar);

        jMenuExcluir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuExcluir.setText("EXCLUSÃO");
        jMenuExcluir.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuExcluirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuExcluir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabelBusca))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPesquisa)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelBusca))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("PuxadaG");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed
        jLabelPesquisa.setText(teclaPress.KeyPuxada(evt));
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if(jTextFieldPesquisa.getText().trim().isEmpty()) {
                manipularJtable.puxada(jTablePuxada,"","1");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Código")) {
                manipularJtable.puxada(jTablePuxada,jTextFieldPesquisa.getText(),"2");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Competição")) {
                manipularJtable.puxada(jTablePuxada,jTextFieldPesquisa.getText(),"7");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Categoria")) {
                manipularJtable.puxada(jTablePuxada,jTextFieldPesquisa.getText(),"9");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Competidor")) {
                manipularJtable.puxada(jTablePuxada,jTextFieldPesquisa.getText(),"10");
            }
            
            if(jTablePuxada.getRowCount() > 0) {
                jTablePuxada.requestFocus();
                jTablePuxada.setRowSelectionInterval(0, 0);
            }
        }
    }//GEN-LAST:event_jTextFieldPesquisaKeyPressed

    private void jLabelBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscaMouseClicked
        // TODO add your handling code here:
//        manipularJtable.puxada(jTablePuxada,"","1");
//        jTablePuxada.requestFocus();
//        jTablePuxada.setRowSelectionInterval(0, 0);
        if(jTextFieldPesquisa.getText().trim().isEmpty()) {
                manipularJtable.puxada(jTablePuxada,"","1");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Código")) {
                manipularJtable.puxada(jTablePuxada,jTextFieldPesquisa.getText(),"2");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Competição")) {
                manipularJtable.puxada(jTablePuxada,jTextFieldPesquisa.getText(),"7");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Categoria")) {
                manipularJtable.puxada(jTablePuxada,jTextFieldPesquisa.getText(),"9");
            } else if(jLabelPesquisa.getText().equals("Pesquisando por Competidor")) {
                manipularJtable.puxada(jTablePuxada,jTextFieldPesquisa.getText(),"10");
            }
            
            if(jTablePuxada.getRowCount() > 0) {
                jTablePuxada.requestFocus();
                jTablePuxada.setRowSelectionInterval(0, 0);
            }
    }//GEN-LAST:event_jLabelBuscaMouseClicked

    private void jMenuAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAlterarMouseClicked
    
    if(jTablePuxada.getSelectedRow() != -1)
     {
    codigo = String.valueOf(jTablePuxada.getValueAt(jTablePuxada.getSelectedRow(),0));
    gerenciapuxada.codigopuxada = codigo;    
    gerenciapuxada.setTitle("Alteração de Puxada");
    gerenciapuxada.setVisible(true); 
    }
    else
    {
        //Exibe Mensagem caso nenhuma linha esteja selecionada
            JOptionPane.showMessageDialog(this, "Selecione uma Puxada na tabela.");
    }
        
}//GEN-LAST:event_jMenuAlterarMouseClicked

    private void jMenuExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExcluirMouseClicked
    
        
    if(jTablePuxada.getSelectedRow() != -1)
    {
        
     codigo = String.valueOf(jTablePuxada.getValueAt(jTablePuxada.getSelectedRow(),0));
    gerenciapuxada.codigopuxada = codigo;    
    gerenciapuxada.setTitle("Exclusão de Puxada");
    gerenciapuxada.setVisible(true); 
    }
    else
    {
    //Exibe Mensagem caso nenhuma linha esteja selecionada
    JOptionPane.showMessageDialog(this, "Selecione uma Puxada na tabela.");    
    }
}//GEN-LAST:event_jMenuExcluirMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       jTextFieldPesquisa.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void jTablePuxadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePuxadaMouseClicked
        
         if ( SwingUtilities.isRightMouseButton( evt ))
            {
                // Pega a posição do click do mouse
                Point p = evt.getPoint();

                // pega o indice da linha que contem as coordenadas iguais ao click do mouse
                int rowNumber = jTablePuxada.rowAtPoint( p );

                // Pega o modelo do Jtable
                ListSelectionModel model = jTablePuxada.getSelectionModel();

                // set the selected interval of rows. Using the "rowNumber"
                // Seleciona um intervalo de linhas
                // variable for the beginning and end selects only that one row.
                // utiliza o mesmo numero para o começo e fim para selecionar a linha especifica
                model.setSelectionInterval( rowNumber, rowNumber );
                jPopupMenuPuxada.setLocation(evt.getLocationOnScreen());
                jPopupMenuPuxada.setVisible(true);
            }
         else
         {
            jPopupMenuPuxada.setVisible(false); 
         }
         

        
        
        
        
    }//GEN-LAST:event_jTablePuxadaMouseClicked

    private void jMenuItemAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemAlterarMouseClicked
       if(jTablePuxada.getSelectedRow() != -1)
     {
    codigo = String.valueOf(jTablePuxada.getValueAt(jTablePuxada.getSelectedRow(),0));
    gerenciapuxada.codigopuxada = codigo;    
    gerenciapuxada.setTitle("Alteração de Puxada");
    gerenciapuxada.setVisible(true); 
    }
   
    }//GEN-LAST:event_jMenuItemAlterarMouseClicked

    private void jMenuItemExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemExcluirMouseClicked
    codigo = String.valueOf(jTablePuxada.getValueAt(jTablePuxada.getSelectedRow(),0));
    gerenciapuxada.codigopuxada = codigo;    
    gerenciapuxada.setTitle("Exclusão de Puxada");
    gerenciapuxada.setVisible(true); 
    }//GEN-LAST:event_jMenuItemExcluirMouseClicked
    
    
    // Código para centralizar
      private void centralizar(){  
      /* Função para centralizar janela na tela */  
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();  
       Dimension frameSize = getSize();  
       setLocation(new Point((screenSize.width - frameSize.width) / 2,  
                             (screenSize.height - frameSize.width) / 2));  
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PuxadaG dialog = new PuxadaG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBusca;
    private javax.swing.JLabel jLabelPesquisa;
    private javax.swing.JMenu jMenuAlterar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuExcluir;
    private javax.swing.JMenuItem jMenuItemAlterar;
    private javax.swing.JMenuItem jMenuItemExcluir;
    private javax.swing.JPopupMenu jPopupMenuPuxada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePuxada;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
    
    
    TeclaPress teclaPress = new TeclaPress();
    ManipularJTable manipularJtable = new ManipularJTable();   
    GerenciaPuxada gerenciapuxada = new GerenciaPuxada(null,true);
    private String codigo ="0";
}
