/*
 * Puxada.java
 *
 * Created on 14 de Agosto de 2007, 10:09
 */
package arrancada.Formularios;

import arrancada.Dao.ServicoBDAO;
import arrancada.Exceptions.MyException;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import arrancada.Util.ValidarCodigoCategoria;
import arrancada.Util.ManipularJTable;
import arrancada.Cronometro.Cronometro;
import java.awt.Color;


/**
 *Data da última alteração - 01/02/2008
 * @author  monitor
 */
public class Puxada extends javax.swing.JDialog {

    /** Creates new form Puxada */
    public Puxada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centralizar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelCompeticao = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldCompeticao = new javax.swing.JTextField();
        jTextFieldCategoria = new javax.swing.JTextField();
        jTextFieldCompeticaoNome = new javax.swing.JTextField();
        jTextFieldCategoriaNome = new javax.swing.JTextField();
        jButtonConsultaCompeticao = new javax.swing.JButton();
        jButtonConsultaCategoria = new javax.swing.JButton();
        jPanelCompetidores = new javax.swing.JPanel();
        jPanelCompetidor1 = new javax.swing.JPanel();
        jLabelCompetidor1 = new javax.swing.JLabel();
        jLabelTempo1 = new javax.swing.JLabel();
        jLabelStatus1 = new javax.swing.JLabel();
        jTextFieldCompetidor1 = new javax.swing.JTextField();
        jTextFieldCompetidor1Nome = new javax.swing.JTextField();
        jTextFieldTempo1 = new javax.swing.JTextField();
        jComboBoxStatus1 = new javax.swing.JComboBox();
        jButtonConsultaCompetidor1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelCompetidor2 = new javax.swing.JLabel();
        jLabelTempo2 = new javax.swing.JLabel();
        jLabelStatus2 = new javax.swing.JLabel();
        jTextFieldCompetidor2 = new javax.swing.JTextField();
        jTextFieldTempo2 = new javax.swing.JTextField();
        jComboBoxStatus2 = new javax.swing.JComboBox();
        jTextFieldCompetidor2Nome = new javax.swing.JTextField();
        jButtonConsultaCompetidor2 = new javax.swing.JButton();
        jPanelBotoes = new javax.swing.JPanel();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jPanelListaClassificacao = new javax.swing.JPanel();
        jScrollPaneListaClassificacao = new javax.swing.JScrollPane();
        jTablePuxada = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Puxada");
        setModal(true);
        setName("Puxada"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCodigo.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelCodigo.setText("Código");

        jLabelCompeticao.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelCompeticao.setText("Competição");

        jLabelCategoria.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelCategoria.setText("Categoria");

        jTextFieldCodigo.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldCodigo.setEditable(false);

        jTextFieldCompeticao.setToolTipText("F12 para consultar Competição.");
        jTextFieldCompeticao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCompeticaoFocusLost(evt);
            }
        });
        jTextFieldCompeticao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCompeticaoKeyPressed(evt);
            }
        });

        jTextFieldCategoria.setToolTipText("F12 para consultar Categoria");
        jTextFieldCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCategoriaFocusLost(evt);
            }
        });
        jTextFieldCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCategoriaKeyPressed(evt);
            }
        });

        jTextFieldCompeticaoNome.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldCompeticaoNome.setEditable(false);
        jTextFieldCompeticaoNome.setFocusable(false);

        jTextFieldCategoriaNome.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldCategoriaNome.setEditable(false);
        jTextFieldCategoriaNome.setFocusable(false);

        jButtonConsultaCompeticao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/botaoconsulta.png"))); // NOI18N
        jButtonConsultaCompeticao.setToolTipText("Consultar Competição.");
        jButtonConsultaCompeticao.setFocusable(false);
        jButtonConsultaCompeticao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaCompeticaoActionPerformed(evt);
            }
        });

        jButtonConsultaCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/botaoconsulta.png"))); // NOI18N
        jButtonConsultaCategoria.setToolTipText("Consultar Categoria.");
        jButtonConsultaCategoria.setFocusable(false);
        jButtonConsultaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaCategoriaActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabelCompeticao)
                    .add(jLabelCodigo)
                    .add(jLabelCategoria))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jTextFieldCompeticao)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jTextFieldCodigo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jTextFieldCategoria, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jButtonConsultaCompeticao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonConsultaCategoria, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTextFieldCompeticaoNome)
                    .add(jTextFieldCategoriaNome, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabelCodigo)
                            .add(jTextFieldCodigo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelCompeticao)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jTextFieldCompeticao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jTextFieldCompeticaoNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jButtonConsultaCompeticao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelCategoria)
                    .add(jTextFieldCategoria, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldCategoriaNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonConsultaCategoria, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanelCompetidores.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelCompetidor1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCompetidor1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelCompetidor1.setText("Competidor1");

        jLabelTempo1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelTempo1.setText("Tempo");

        jLabelStatus1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelStatus1.setText("Status");

        jTextFieldCompetidor1.setToolTipText("F12 para consultar Competidor.");
        jTextFieldCompetidor1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCompetidor1FocusLost(evt);
            }
        });

        jTextFieldCompetidor1Nome.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldCompetidor1Nome.setEditable(false);
        jTextFieldCompetidor1Nome.setFocusable(false);

        jTextFieldTempo1.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldTempo1.setEditable(false);
        jTextFieldTempo1.setFocusable(false);

        jComboBoxStatus1.setFont(new java.awt.Font("Tahoma", 1, 10));
        jComboBoxStatus1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Largada Queimada", "Desclassificado", "Sem Competidor" }));
        jComboBoxStatus1.setFocusable(false);

        jButtonConsultaCompetidor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/botaoconsulta.png"))); // NOI18N
        jButtonConsultaCompetidor1.setToolTipText("Consultar Categoria.");
        jButtonConsultaCompetidor1.setFocusable(false);
        jButtonConsultaCompetidor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaCompetidor1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelCompetidor1Layout = new org.jdesktop.layout.GroupLayout(jPanelCompetidor1);
        jPanelCompetidor1.setLayout(jPanelCompetidor1Layout);
        jPanelCompetidor1Layout.setHorizontalGroup(
            jPanelCompetidor1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelCompetidor1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelCompetidor1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabelTempo1)
                    .add(jLabelStatus1)
                    .add(jLabelCompetidor1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelCompetidor1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanelCompetidor1Layout.createSequentialGroup()
                        .add(jTextFieldCompetidor1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonConsultaCompetidor1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextFieldCompetidor1Nome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jComboBoxStatus1, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jTextFieldTempo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCompetidor1Layout.setVerticalGroup(
            jPanelCompetidor1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelCompetidor1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelCompetidor1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelCompetidor1Layout.createSequentialGroup()
                        .add(jPanelCompetidor1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanelCompetidor1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jTextFieldCompetidor1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jLabelCompetidor1))
                            .add(jButtonConsultaCompetidor1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanelCompetidor1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabelTempo1)
                            .add(jTextFieldTempo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jTextFieldCompetidor1Nome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelCompetidor1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBoxStatus1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelStatus1))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCompetidor2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelCompetidor2.setText("Competidor2");

        jLabelTempo2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelTempo2.setText("Tempo");

        jLabelStatus2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelStatus2.setText("Status");

        jTextFieldCompetidor2.setToolTipText("F12 para consultar Competidor.");
        jTextFieldCompetidor2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCompetidor2FocusLost(evt);
            }
        });

        jTextFieldTempo2.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldTempo2.setEditable(false);
        jTextFieldTempo2.setFocusable(false);

        jComboBoxStatus2.setFont(new java.awt.Font("Tahoma", 1, 10));
        jComboBoxStatus2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Largada Queimada", "Desclassificado", "Sem Competidor" }));
        jComboBoxStatus2.setFocusable(false);

        jTextFieldCompetidor2Nome.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldCompetidor2Nome.setEditable(false);

        jButtonConsultaCompetidor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/botaoconsulta.png"))); // NOI18N
        jButtonConsultaCompetidor2.setToolTipText("Consultar Categoria.");
        jButtonConsultaCompetidor2.setFocusable(false);
        jButtonConsultaCompetidor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaCompetidor2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabelCompetidor2)
                    .add(jLabelStatus2)
                    .add(jLabelTempo2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jTextFieldCompetidor2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonConsultaCompetidor2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 31, Short.MAX_VALUE)
                        .add(jTextFieldCompetidor2Nome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jComboBoxStatus2, 0, 259, Short.MAX_VALUE)
                    .add(jTextFieldTempo2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabelCompetidor2)
                        .add(jTextFieldCompetidor2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jTextFieldCompetidor2Nome))
                    .add(jButtonConsultaCompetidor2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelTempo2)
                    .add(jTextFieldTempo2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBoxStatus2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelStatus2))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanelCompetidoresLayout = new org.jdesktop.layout.GroupLayout(jPanelCompetidores);
        jPanelCompetidores.setLayout(jPanelCompetidoresLayout);
        jPanelCompetidoresLayout.setHorizontalGroup(
            jPanelCompetidoresLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelCompetidoresLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelCompetidor1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCompetidoresLayout.setVerticalGroup(
            jPanelCompetidoresLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelCompetidoresLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelCompetidoresLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanelCompetidor1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonAtualizar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonConfirmar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButtonConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/14.png"))); // NOI18N
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/06.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonFechar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/15.png"))); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFecharMouseClicked(evt);
            }
        });
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelBotoesLayout = new org.jdesktop.layout.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .add(jButtonAtualizar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 288, Short.MAX_VALUE)
                .add(jButtonConfirmar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButtonCancelar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonFechar)
                .add(21, 21, 21))
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jButtonAtualizar)
                .add(jButtonConfirmar)
                .add(jButtonFechar)
                .add(jButtonCancelar))
        );

        jPanelListaClassificacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPaneListaClassificacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTablePuxada.setAutoCreateRowSorter(true);
        jTablePuxada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Competição", "Categoria", "Competidor", "Tempo", "Status", "Puxada"
            }
        ));
        jTablePuxada.getTableHeader().setReorderingAllowed(false);
        jScrollPaneListaClassificacao.setViewportView(jTablePuxada);

        org.jdesktop.layout.GroupLayout jPanelListaClassificacaoLayout = new org.jdesktop.layout.GroupLayout(jPanelListaClassificacao);
        jPanelListaClassificacao.setLayout(jPanelListaClassificacaoLayout);
        jPanelListaClassificacaoLayout.setHorizontalGroup(
            jPanelListaClassificacaoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelListaClassificacaoLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPaneListaClassificacao, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelListaClassificacaoLayout.setVerticalGroup(
            jPanelListaClassificacaoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelListaClassificacaoLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPaneListaClassificacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 259, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanelBotoes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanelCompetidores, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanelListaClassificacao, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelCompetidores, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanelBotoes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelListaClassificacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFecharMouseClicked
    dispose();
}//GEN-LAST:event_jButtonFecharMouseClicked

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        try 
        {
            Cronometro cronometro = new Cronometro();
            String[] tempo = {null, null};
            tempo = cronometro.lerTXT();
             
            if(((tempo[0]==null)&&(tempo[1]==null)) || ((tempo[0].isEmpty())&&(tempo[1].isEmpty())))
            {
             JOptionPane.showMessageDialog(this,"Arquivo não existe ou não foi gerado corretamente");   
            }else
            {
            
            jTextFieldTempo1.setText(tempo[0]=(tempo[0].substring(tempo[0].indexOf(";")+1)));
            jTextFieldTempo2.setText(tempo[1]=(tempo[1].substring(tempo[1].indexOf(";")+1)));
            }
        } 
        catch (MyException ex) 
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
}                                                

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(evt.getOppositeWindow() instanceof Principal)
        {
            ResultSet rs = null;
            String zeros = "0000"+servico.proximoCodigo("puxada");
            jTextFieldCodigo.setText(zeros.substring(zeros.length()-4));
            jTextFieldCodigo.setEnabled(false);
            atualizarjTable();
            try
            {
                rs = servico.selectCompeticao("nulo", "4");
                if(rs.next() != false)
                {
                    jTextFieldCompeticao.setText(rs.getString(1));
                    jTextFieldCompeticaoNome.setText(rs.getString(2));
                    jTextFieldCompeticao.transferFocus();
                }
                
            }
            catch (SQLException ex) 
            {
                Logger.getLogger(ValidarCodigoCategoria.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally
            {
                try 
                {
                    rs.close();
                } 
                catch (SQLException ex) 
                {
                    Logger.getLogger(Puxada.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    }//GEN-LAST:event_formWindowActivated

    private void jTextFieldCategoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCategoriaFocusLost
        ResultSet rs = null;
        jTextFieldCategoriaNome.setText("");
        if(!jTextFieldCategoria.getText().equals(""))
        {
            try
            {
                rs = servico.selectCategoria(jTextFieldCategoria.getText().trim(), "1");
                if(rs.next() != false)
                {
                    jTextFieldCategoriaNome.setText(rs.getString(2));
                    jTextFieldCategoriaNome.setForeground(Color.BLACK);
                }
                else
                {
                    jTextFieldCategoriaNome.setText("Categoria não encontrada");
                    jTextFieldCategoriaNome.setForeground(Color.RED);
                }
            }
            catch (SQLException ex) 
            {
                Logger.getLogger(ValidarCodigoCategoria.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally
            {
                try 
                {
                    rs.close();
                } 
                catch (SQLException ex) 
                {
                    Logger.getLogger(Puxada.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jTextFieldCategoriaFocusLost

    //devido a um aparente bug do JoptionPane, o jTextFieldCompetidor1Nome teve que ficar com o foco habilitado
    //obrigando assim a chamar o método transferfocus.
    private void jTextFieldCompetidor1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCompetidor1FocusLost
        if(evt.getOppositeComponent() instanceof JOptionPane)
        {
            return;
        }
        else
        {
            jTextFieldCompetidor1Nome.setText("");
            if(!jTextFieldCompetidor1.getText().trim().equals(""))
            {
                ResultSet rs = null;
                try
                {
                    rs = servico.selectCompetidor(jTextFieldCompetidor1.getText().trim(),"","","7");
                    if(rs.next() != false)
                    {
                        jTextFieldCompetidor1Nome.setText(rs.getString(4));
                        jTextFieldCompetidor1Nome.setForeground(Color.BLACK);
                        jTextFieldCompetidor1Nome.transferFocus();
                    }
                    else
                    {
                        jTextFieldCompetidor1Nome.setText("Competidor não Encontrado");
                        jTextFieldCompetidor1Nome.setForeground(Color.RED);
                    }
                }
                catch (SQLException ex) 
                {
                    Logger.getLogger(ValidarCodigoCategoria.class.getName()).log(Level.SEVERE, null, ex);
                }
                finally
                {
                    try 
                    {
                        rs.close();
                    } 
                    catch (SQLException ex) 
                    {
                        Logger.getLogger(Puxada.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_jTextFieldCompetidor1FocusLost

    //devido a um aparente bug do JoptionPane, o jTextFieldCompetidor2Nome teve que ficar com o foco habilitado
    //obrigando assim a chamar o método transferfocus.
    private void jTextFieldCompetidor2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCompetidor2FocusLost
        if(evt.getOppositeComponent() instanceof JOptionPane)
        {
            return;
        }
        else
        {
            jTextFieldCompetidor2Nome.setText("");
            if(!jTextFieldCompetidor2.getText().trim().equals(""))
            {
                ResultSet rs = null;
                try
                {
                    rs = servico.selectCompetidor(jTextFieldCompetidor2.getText().trim(),"","","7");
                    if(rs.next() != false)
                    {
                        jTextFieldCompetidor2Nome.setText(rs.getString(4));
                        jTextFieldCompetidor2Nome.setForeground(Color.BLACK);
                        jTextFieldCompetidor2Nome.transferFocus();
                    }
                    else
                    {
                        jTextFieldCompetidor2Nome.setText("Competidor não Encontrado");
                        jTextFieldCompetidor2Nome.setForeground(Color.RED);
                    }
                }
                catch (SQLException ex) 
                {
                    Logger.getLogger(ValidarCodigoCategoria.class.getName()).log(Level.SEVERE, null, ex);
                }
                finally
                {
                    try 
                    {
                        rs.close();
                    } 
                    catch (SQLException ex) 
                    {
                        Logger.getLogger(Puxada.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_jTextFieldCompetidor2FocusLost

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldCompetidor1.setText("");
        jTextFieldCompetidor1Nome.setText("");
        jTextFieldCompetidor2.setText("");
        jTextFieldCompetidor2Nome.setText("");
        jTextFieldTempo1.setText("");
        jTextFieldTempo2.setText("");
        jComboBoxStatus1.setSelectedItem("Normal");
        jComboBoxStatus2.setSelectedItem("Normal");
        jTextFieldCompetidor1.requestFocus();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        jTextFieldCategoria.setText("");
        jTextFieldCategoriaNome.setText("");
        jTextFieldCompetidor1.setText("");
        jTextFieldCompetidor1Nome.setText("");
        jTextFieldCompetidor2.setText("");
        jTextFieldCompetidor2Nome.setText("");
        jTextFieldTempo1.setText("");
        jTextFieldTempo2.setText("");
        jComboBoxStatus1.setSelectedItem("Normal");
        jComboBoxStatus2.setSelectedItem("Normal");
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
       if (jTextFieldCompeticaoNome.getText().equals("Competição não encontrada") || jTextFieldCompeticaoNome.getText().equals("")) 
       {
           jTextFieldCompeticao.requestFocus();
           JOptionPane.showMessageDialog(this, "Você deve informar uma Competição válida.", "Competição não encontrada", JOptionPane.INFORMATION_MESSAGE);
           return;
       }
        
       if(jTextFieldCategoriaNome.getText().equals("Categoria não encontrada") || jTextFieldCategoriaNome.getText().equals(""))
       {
           jTextFieldCategoria.requestFocus();
           JOptionPane.showMessageDialog(this, "Você deve informar uma Categoria cadastrada.","Categoria não encontrada",JOptionPane.INFORMATION_MESSAGE);
           return;
       }
        
       if(jTextFieldCompetidor1Nome.getText().equals("Competidor não Encontrado") || jTextFieldCompetidor1Nome.getText().equals("") && !jComboBoxStatus1.getSelectedItem().equals("Sem Competidor"))
       {
           jTextFieldCompetidor1.requestFocus();
           JOptionPane.showMessageDialog(this, "Você deve informar um Competidor cadastrado.","Competidor 1 não encontrado",JOptionPane.INFORMATION_MESSAGE);
           return;
       }
       
       if(jTextFieldCompetidor2Nome.getText().equals("Competidor não Encontrado") || jTextFieldCompetidor2Nome.getText().equals("") && !jComboBoxStatus2.getSelectedItem().equals("Sem Competidor"))
       {
           jTextFieldCompetidor2.requestFocus();
           JOptionPane.showMessageDialog(this, "Você deve informar um Competidor cadastrado.","Competidor 2 não encontrado",JOptionPane.INFORMATION_MESSAGE);
           return;
       }
        
       if(jTextFieldCompetidor1.getText().trim().equals(jTextFieldCompetidor2.getText().trim())) 
       {
           jTextFieldCompetidor1.requestFocus();
           JOptionPane.showMessageDialog(this, "Competidor 1 igual ao Competidor 2.", "Competidores Iguais", JOptionPane.INFORMATION_MESSAGE);
           return;
       }
        
       if(jTextFieldTempo1.getText().equals("Competidor não Encontrado") || jTextFieldTempo1.getText().equals("") && !jComboBoxStatus1.getSelectedItem().equals("Sem Competidor"))
       {
           jButtonAtualizar.requestFocus();
           JOptionPane.showMessageDialog(this, "Tempo do Competidor 1 inválido.","Tempo 1 não encontrado",JOptionPane.INFORMATION_MESSAGE);
           return;
       }
       if(jTextFieldTempo2.getText().equals("Competidor não Encontrado") || jTextFieldTempo2.getText().equals("") && !jComboBoxStatus2.getSelectedItem().equals("Sem Competidor"))
       {
           jButtonAtualizar.requestFocus();
           JOptionPane.showMessageDialog(this, "Tempo do Competidor 2 inválido.","Tempo 2 não encontrado",JOptionPane.INFORMATION_MESSAGE);
           return;
       }
       
       if(!jComboBoxStatus1.getSelectedItem().equals("Sem Competidor"))
       {
            String numPuxada = servico.proximaPuxada(jTextFieldCompeticao.getText(),jTextFieldCategoria.getText(),jTextFieldCompetidor1.getText());
            int x = servico.insertPuxada(String.valueOf(Integer.parseInt(jTextFieldCodigo.getText().trim())), jTextFieldCompeticao.getText().trim(), jTextFieldCategoria.getText().trim(), jTextFieldCompetidor1.getText().trim(), jTextFieldTempo1.getText().trim(), jComboBoxStatus1.getSelectedItem().toString(), numPuxada);
            if(x == 1)
            {
               String numPuxada2 = servico.proximaPuxada(jTextFieldCompeticao.getText(),jTextFieldCategoria.getText(),jTextFieldCompetidor2.getText()); 
               int z = servico.insertPuxada(String.valueOf(Integer.parseInt(jTextFieldCodigo.getText().trim())+1), jTextFieldCompeticao.getText().trim(), jTextFieldCategoria.getText().trim(), jTextFieldCompetidor2.getText().trim(), jTextFieldTempo2.getText().trim(), jComboBoxStatus2.getSelectedItem().toString(), numPuxada2);
               if(z == 1)
               {
                   atualizarjTable();
                   String zeros = "0000"+servico.proximoCodigo("puxada");
                   jTextFieldCodigo.setText(zeros.substring(zeros.length()-4));
                   JOptionPane.showMessageDialog(this, "Puxada cadastrada com sucesso.","Puxada cadastrada com sucesso.",JOptionPane.INFORMATION_MESSAGE);
               }
            }
       }
       else if(!jComboBoxStatus2.getSelectedItem().equals("Sem Competidor"))
       {
           String numPuxada2 = servico.proximaPuxada(jTextFieldCompeticao.getText(),jTextFieldCategoria.getText(),jTextFieldCompetidor2.getText()); 
           int z = servico.insertPuxada(String.valueOf(Integer.parseInt(jTextFieldCodigo.getText().trim())+1), jTextFieldCompeticao.getText().trim(), jTextFieldCategoria.getText().trim(), jTextFieldCompetidor2.getText().trim(), jTextFieldTempo2.getText().trim(), jComboBoxStatus2.getSelectedItem().toString(), numPuxada2);
           if(z == 1)
           {
                atualizarjTable();
                String zeros = "0000"+servico.proximoCodigo("puxada");
                jTextFieldCodigo.setText(zeros.substring(zeros.length()-4));
                JOptionPane.showMessageDialog(this, "Puxada cadastrada com sucesso.","Puxada cadastrada com sucesso.",JOptionPane.INFORMATION_MESSAGE);
           }
       }
       else
       {
           JOptionPane.showMessageDialog(this, "Nenhum Competidor informado.","Informe um Competidor.",JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonConsultaCompeticaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaCompeticaoActionPerformed
        janelaConsultaCompeticao();
    }//GEN-LAST:event_jButtonConsultaCompeticaoActionPerformed

    private void jTextFieldCompeticaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCompeticaoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_F12)
        {
            janelaConsultaCompeticao();
        }
    }//GEN-LAST:event_jTextFieldCompeticaoKeyPressed

    private void jTextFieldCompeticaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCompeticaoFocusLost
        ResultSet rs = null;
        jTextFieldCompeticaoNome.setText("");
        if(!jTextFieldCompeticao.getText().equals(""))
        {
            try
            {
                rs = servico.selectCompeticao(jTextFieldCompeticao.getText().trim(), "1");
                if(rs.next() != false)
                {
                    jTextFieldCompeticaoNome.setText(rs.getString(2));
                    jTextFieldCompeticaoNome.setForeground(Color.BLACK);
                }
                else
                {
                    jTextFieldCompeticaoNome.setText("Competição não encontrada");
                    jTextFieldCompeticaoNome.setForeground(Color.RED);
                }
            }
            catch (SQLException ex) 
            {
                Logger.getLogger(ValidarCodigoCategoria.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally
            {
                try 
                {
                    rs.close();
                } 
                catch (SQLException ex) 
                {
                    Logger.getLogger(Puxada.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jTextFieldCompeticaoFocusLost

    private void jTextFieldCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCategoriaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_F12)
        {
            janelaConsultaCategoria();
        }
    }//GEN-LAST:event_jTextFieldCategoriaKeyPressed

    private void jButtonConsultaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaCategoriaActionPerformed
        janelaConsultaCategoria();
    }//GEN-LAST:event_jButtonConsultaCategoriaActionPerformed

    private void jButtonConsultaCompetidor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaCompetidor2ActionPerformed
        // TODO add your handling code here:
    ConsultaCompetidor consultacompetidor = new ConsultaCompetidor(null, true);
    consultacompetidor.setVisible(true);    
    jTextFieldCompetidor2.setText(Integer.toString(consultacompetidor.codigo));
    jTextFieldCompetidor2.requestFocus();
}//GEN-LAST:event_jButtonConsultaCompetidor2ActionPerformed

    private void jButtonConsultaCompetidor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaCompetidor1ActionPerformed
        // TODO add your handling code here:
        
    ConsultaCompetidor consultacompetidor = new ConsultaCompetidor(null, true);
    consultacompetidor.setVisible(true);    
    jTextFieldCompetidor1.setText(Integer.toString(consultacompetidor.codigo));
    jTextFieldCompetidor1.requestFocus();

        
}//GEN-LAST:event_jButtonConsultaCompetidor1ActionPerformed
    
    private void janelaConsultaCompeticao()
    {
        ConsultaCompeticao consultaCompeticao = new ConsultaCompeticao(null, true);
        consultaCompeticao.setVisible(true);
        jTextFieldCompeticao.setText(Integer.toString(consultaCompeticao.codigo));
        jTextFieldCompeticao.transferFocus();
    }
    
    private void janelaConsultaCategoria()
    {
        ConsultaCategoria consultaCategoria = new ConsultaCategoria(null, true);
        consultaCategoria.setVisible(true);
        jTextFieldCategoria.setText(Integer.toString(consultaCategoria.codigo));
        jTextFieldCategoria.transferFocus();
        
    }
    
    private void atualizarjTable()
    {
        manipularJTable.puxada(jTablePuxada,"","1");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Puxada dialog = new Puxada(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
   private void centralizar(){  
      /* Função para centralizar janela na tela */  
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();  
       Dimension frameSize = getSize();  
       setLocation(new Point((screenSize.width - frameSize.width) / 2,  
                             (screenSize.height - frameSize.width) / 2));  
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonConsultaCategoria;
    private javax.swing.JButton jButtonConsultaCompeticao;
    private javax.swing.JButton jButtonConsultaCompetidor1;
    private javax.swing.JButton jButtonConsultaCompetidor2;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JComboBox jComboBoxStatus1;
    private javax.swing.JComboBox jComboBoxStatus2;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCompeticao;
    private javax.swing.JLabel jLabelCompetidor1;
    private javax.swing.JLabel jLabelCompetidor2;
    private javax.swing.JLabel jLabelStatus1;
    private javax.swing.JLabel jLabelStatus2;
    private javax.swing.JLabel jLabelTempo1;
    private javax.swing.JLabel jLabelTempo2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelCompetidor1;
    private javax.swing.JPanel jPanelCompetidores;
    private javax.swing.JPanel jPanelListaClassificacao;
    private javax.swing.JScrollPane jScrollPaneListaClassificacao;
    private javax.swing.JTable jTablePuxada;
    private javax.swing.JTextField jTextFieldCategoria;
    private javax.swing.JTextField jTextFieldCategoriaNome;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCompeticao;
    private javax.swing.JTextField jTextFieldCompeticaoNome;
    private javax.swing.JTextField jTextFieldCompetidor1;
    private javax.swing.JTextField jTextFieldCompetidor1Nome;
    private javax.swing.JTextField jTextFieldCompetidor2;
    private javax.swing.JTextField jTextFieldCompetidor2Nome;
    private javax.swing.JTextField jTextFieldTempo1;
    private javax.swing.JTextField jTextFieldTempo2;
    // End of variables declaration//GEN-END:variables
    
    ServicoBDAO servico = new ServicoBDAO();
    ManipularJTable manipularJTable = new ManipularJTable();
    private int clicouBotaoPesquisa = 0;
       
   
}
