/*
 * Veiculo.java
 *
 * Created on 14 de Agosto de 2007, 08:51
 */

package arrancada.Formularios;

import arrancada.Relatorios.GeraRelatorio;
import arrancada.Util.TeclaPress;
import arrancada.Util.ManipularJTable;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author  monitor
 */
public class Veiculo extends javax.swing.JDialog {
    
    /** Creates new form Veiculo */
    public Veiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centralizar();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPaneVeiculo = new javax.swing.JScrollPane();
        jTableVeiculo = new javax.swing.JTable();
        jLabelPesquisa = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jLabelBusca = new javax.swing.JLabel();
        jMenuBarVeiculo = new javax.swing.JMenuBar();
        jMenuInclusao = new javax.swing.JMenu();
        jMenuAlteracao = new javax.swing.JMenu();
        jMenuExclusao = new javax.swing.JMenu();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuFechar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Veículo");
        setFocusable(false);
        setModal(true);
        setName("Veiculo"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("[F2] Código    [F3] Nome     [F4] Tipo Veiculo");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jScrollPaneVeiculo.setFocusable(false);

        jTableVeiculo.setAutoCreateRowSorter(true);
        jTableVeiculo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Tipo"
            }
        ));
        jTableVeiculo.getTableHeader().setReorderingAllowed(false);
        jTableVeiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableVeiculoKeyPressed(evt);
            }
        });
        jScrollPaneVeiculo.setViewportView(jTableVeiculo);

        jLabelPesquisa.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelPesquisa.setText("Pesquisando por Código:");

        jTextFieldPesquisa.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
        });

        jLabelBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrancada.Imagens/search_f2.png"))); // NOI18N
        jLabelBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBuscaMouseClicked(evt);
            }
        });

        jMenuBarVeiculo.setBorder(null);

        jMenuInclusao.setMnemonic(KeyEvent.VK_I);
        jMenuInclusao.setText("INCLUSÃO");
        jMenuInclusao.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuInclusao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuInclusaoMouseClicked(evt);
            }
        });
        jMenuBarVeiculo.add(jMenuInclusao);

        jMenuAlteracao.setMnemonic(KeyEvent.VK_A);
        jMenuAlteracao.setText("ALTERAÇÃO");
        jMenuAlteracao.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuAlteracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAlteracaoMouseClicked(evt);
            }
        });
        jMenuBarVeiculo.add(jMenuAlteracao);

        jMenuExclusao.setMnemonic(KeyEvent.VK_E);
        jMenuExclusao.setText("EXCLUSÃO");
        jMenuExclusao.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuExclusao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuExclusaoMouseClicked(evt);
            }
        });
        jMenuBarVeiculo.add(jMenuExclusao);

        jMenuRelatorio.setMnemonic(KeyEvent.VK_R);
        jMenuRelatorio.setText("RELATÓRIO");
        jMenuRelatorio.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuRelatorioMouseClicked(evt);
            }
        });
        jMenuBarVeiculo.add(jMenuRelatorio);

        jMenuFechar.setMnemonic(KeyEvent.VK_F);
        jMenuFechar.setText("FECHAR");
        jMenuFechar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenuFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuFecharMouseClicked(evt);
            }
        });
        jMenuBarVeiculo.add(jMenuFechar);

        setJMenuBar(jMenuBarVeiculo);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelPesquisa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 175, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jTextFieldPesquisa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 211, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabelBusca, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(jScrollPaneVeiculo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPaneVeiculo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabelPesquisa)
                        .add(jTextFieldPesquisa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabelBusca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

                                              

private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed
    jLabelPesquisa.setText(teclaPress.KeyVeiculo(evt));
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {        
        //manipularJtable.selecionarValor(jTableCategoria, jTextFieldPesquisa.getText(), 0);
        if(jTextFieldPesquisa.getText().trim().isEmpty())
        {
//            System.out.println(jTableVeiculo.getColumnModel().getColumn(0).getWidth());
//            System.out.println(jTableVeiculo.getColumnModel().getColumn(1).getWidth());
//            System.out.println(jTableVeiculo.getColumnModel().getColumn(2).getWidth());

           manipularJTable.veiculo(jTableVeiculo, "", "0");
        }
        else if(jLabelPesquisa.getText().equals("Pesquisando por Código"))
        {
            manipularJTable.veiculo(jTableVeiculo, jTextFieldPesquisa.getText(), "1");
        }
        else if(jLabelPesquisa.getText().equals("Pesquisando por Nome"))
        {
            manipularJTable.veiculo(jTableVeiculo, jTextFieldPesquisa.getText(), "2");
        }
        else if(jLabelPesquisa.getText().equals("Pesquisando por Tipo Veículo"))
        {
            manipularJTable.veiculo(jTableVeiculo, jTextFieldPesquisa.getText(), "3");
        }
        if(jTableVeiculo.getRowCount() > 0)
        {
            jTableVeiculo.requestFocus();
            jTableVeiculo.setRowSelectionInterval(0, 0);
        }
    }       
}//GEN-LAST:event_jTextFieldPesquisaKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jTextFieldPesquisa.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void jLabelBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscaMouseClicked
        // TODO add your handling code here:
    if(jTextFieldPesquisa.getText().trim().isEmpty())
    {
        manipularJTable.veiculo(jTableVeiculo, "", "0");
    }
    else if(jLabelPesquisa.getText().equals("Pesquisando por Código"))
    {
        manipularJTable.veiculo(jTableVeiculo, jTextFieldPesquisa.getText(), "1");
    }
    else if(jLabelPesquisa.getText().equals("Pesquisando por Nome"))
    {
        manipularJTable.veiculo(jTableVeiculo, jTextFieldPesquisa.getText(), "2");
    }
    jTableVeiculo.requestFocus();
    jTableVeiculo.setRowSelectionInterval(0, 0);
    }//GEN-LAST:event_jLabelBuscaMouseClicked

    private void jMenuAlteracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAlteracaoMouseClicked
       // Se a linha for == -1 siginifica que não tem linha selecionada
        if(jTableVeiculo.getSelectedRow() != -1)
        {
            //Altera o Título da janela
            gerenciaveiculo.setTitle("Alteração de Veículo");
            gerenciaveiculo.clikmenu = "1";
            gerenciaveiculo.codigo = String.valueOf(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow() ,0));
            gerenciaveiculo.setVisible(true);
        }
        else
        {
            //Exibe Mensagem caso nenhuma linha esteja selecionada
            JOptionPane.showMessageDialog(null, "Selecione um Veículo na tabela.");
        }   
    }//GEN-LAST:event_jMenuAlteracaoMouseClicked

    private void jMenuExclusaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExclusaoMouseClicked
        // Se a linha for == -1 siginifica que não tem linha selecionada
        if(jTableVeiculo.getSelectedRow() != -1)
        {
            gerenciaveiculo.setTitle("Exclusão de Veículo");
            gerenciaveiculo.clikmenu = "2";
            gerenciaveiculo.codigo = String.valueOf(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow() ,0));
            gerenciaveiculo.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Selecione um Veículo na tabela.");
        }       
    }//GEN-LAST:event_jMenuExclusaoMouseClicked

    private void jMenuFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuFecharMouseClicked
        dispose();
    }//GEN-LAST:event_jMenuFecharMouseClicked

    private void jMenuInclusaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuInclusaoMouseClicked
        // TODO add your handling code here:
        gerenciaveiculo.setTitle("Inclusão de Veículo");
        gerenciaveiculo.clikmenu = "0";
        gerenciaveiculo.setVisible(true); 
}//GEN-LAST:event_jMenuInclusaoMouseClicked

    private void jMenuRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuRelatorioMouseClicked
//           try {
//
//             new GeraRelatorio().montaRelatorio(5,"Veículo");
//              
//             } catch (JRException ex)
//             {
//             JOptionPane.showMessageDialog(null,ex.getMessage());              
//              }
        new ConfiguraRelatorioVeiculo(null,true).setVisible(true);
    }//GEN-LAST:event_jMenuRelatorioMouseClicked

    private void jTableVeiculoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableVeiculoKeyPressed
        if((evt.getKeyCode() == KeyEvent.VK_F2) ||(evt.getKeyCode() == KeyEvent.VK_F3)) 
        {
            jLabelPesquisa.setText(teclaPress.KeyVeiculo(evt));
            jTextFieldPesquisa.requestFocus();
        }
    }//GEN-LAST:event_jTableVeiculoKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Veiculo dialog = new Veiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
  private void centralizar(){  
      /* Função para centralizar janela na tela */  
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();  
       Dimension frameSize = getSize();  
       setLocation(new Point((screenSize.width - frameSize.width) / 2,  
                             (screenSize.height - frameSize.width) / 2));  
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBusca;
    private javax.swing.JLabel jLabelPesquisa;
    private javax.swing.JMenu jMenuAlteracao;
    private javax.swing.JMenuBar jMenuBarVeiculo;
    private javax.swing.JMenu jMenuExclusao;
    private javax.swing.JMenu jMenuFechar;
    private javax.swing.JMenu jMenuInclusao;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JScrollPane jScrollPaneVeiculo;
    private javax.swing.JTable jTableVeiculo;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
    
    GerenciaVeiculo gerenciaveiculo = new GerenciaVeiculo(null,true);
    ManipularJTable manipularJTable = new ManipularJTable();
    TeclaPress teclaPress = new TeclaPress();
    int cont = 0;
}
